const http = require('http');
const crypto = require('crypto');
const { URL } = require('url');

const PORT = Number(process.env.PORT || 10000);
const SECRET = process.env.XSPORTSX_CONFIG_SECRET || 'change-this-in-render';
const KEY = crypto.createHash('sha256').update(SECRET).digest();
const VERSION = '9.6.0';
const CACHE = new Map();

const LEAGUES = [
  ['nfl','NFL','🏈','football','nfl',['NFL','NFL Network','NFL RedZone','CBS','Paramount+','FOX','FOX One','NBC','Peacock','ESPN','ABC','Prime Video','Amazon Prime','Netflix']],
  ['ncaaf','NCAA Football','🏈','football','college-football',['ESPN','ESPN+','ESPN2','ESPNU','SEC Network','ACC Network','Big Ten Network','CBS','CBS Sports Network','FOX','FOX One','FS1','FS2','NBC','ABC','Peacock','TNT','TBS','truTV','The CW','FloSports','HBCUGO','NEC Front Row']],
  ['nba','NBA','🏀','basketball','nba',['ESPN','ESPN2','ABC','NBA TV','TNT','TBS','NBC','NBCSN','Peacock','Prime Video','Amazon Prime','FanDuel Sports Network','SportsNet','Spectrum SportsNet','YES','MSG','Bally']],
  ['wnba','WNBA','🏀','basketball','wnba',['ESPN','ESPN2','ABC','CBS','ION','NBA TV','Prime Video','Amazon Prime','CBS Sports Network']],
  ['ncaab','NCAA Basketball','🏀','basketball','mens-college-basketball',['ESPN','ESPN+','ESPN2','ESPNU','SEC Network','ACC Network','Big Ten Network','CBS','CBS Sports Network','FOX','FS1','FS2','TNT','TBS','truTV','NBC','Peacock','ABC']],
  ['mlb','MLB','⚾','baseball','mlb',['ESPN','ESPN2','FOX','FS1','FOX Deportes','TBS','MLB Network','NBC','NBC Sports','Peacock','Apple TV','Apple TV+','Netflix','FOX Sports','ABC','FanDuel Sports Network','SportsNet','Sportsnet','YES','SNY','NESN','MASN','Marquee Sports Network','CHSN','Spectrum SportsNet','SportsNet LA','NBC Sports Bay Area','NBC Sports California','NBC Sports Chicago','NBC Sports Philadelphia','NBC Sports Boston','NBC Sports Washington','Bally','AT&T SportsNet','Altitude Sports','Space City Home Network','Rogers Sportsnet','Sportsnet+','MLB.TV']],
  ['nhl','NHL','🏒','hockey','nhl',['ESPN','ESPN+','TNT','TBS','ABC','Hulu','NHL Network','NBC','Peacock','SportsNet','Sportsnet','TSN','TSN2','TSN 3','TSN 4','TSN 5','FanDuel Sports Network','NESN','SNY','MSG','YES','Altitude Sports','Victory+','CHSN','Root Sports']],
  ['mls','MLS','⚽','soccer','usa.1',['Apple TV','Apple TV+','FOX','FS1','FS2','FOX Deportes','ESPN','ESPN2','ABC','TNT','TBS','CBS','Paramount+','Peacock','Telemundo','Univision','TUDN','FOX Sports']],
  ['epl','Premier League','⚽','soccer','eng.1',['NBC','Peacock','USA Network','NBC Sports','NBCSN','Telemundo','Universo','Sky Sports','TNT Sports','ESPN','ESPN+']],
  ['ucl','UEFA Champions League','⚽','soccer','uefa.champions',['Paramount+','CBS','TNT Sports','TNT','TBS','Univision','TUDN','DAZN','ESPN','ESPN+','beIN Sports']],
  ['laliga','LaLiga','⚽','soccer','esp.1',['ESPN','ESPN+','ESPN Deportes','ABC','ESPN2','DAZN','beIN Sports']],
  ['seriea','Serie A','⚽','soccer','ita.1',['CBS','Paramount+','TUDN','Univision','DAZN','ESPN+']],
  ['bundesliga','Bundesliga','⚽','soccer','ger.1',['ESPN','ESPN+','ESPN Deportes','DAZN','Sky Sports']],
  ['ligue1','Ligue 1','⚽','soccer','fra.1',['beIN Sports','beIN Sports en Español','DAZN','ESPN+','TNT Sports']],
  ['ufc','UFC','🥊','mma','ufc',['Paramount+','CBS','TSN','TSN2','TSN 3','TSN 4','TSN 5','ESPN','ESPN+','TNT Sports','Sportsnet','UFC Fight Pass']],
  ['boxing','Boxing','🥊','boxing','boxing',['DAZN','ESPN','ESPN+','Prime Video','Amazon Prime','PBC','FOX','FOX One','CBS','Paramount+','TNT Sports','TNT','TBS','Top Rank','ESPN Deportes','TSN','TSN2']]
];
const VALID = new Set(LEAGUES.map(x=>x[0]));
const LEAGUE = id => LEAGUES.find(x=>x[0]===id);

function headers(res,type='application/json; charset=utf-8'){
  res.setHeader('access-control-allow-origin','*');
  res.setHeader('access-control-allow-methods','GET,POST,OPTIONS');
  res.setHeader('access-control-allow-headers','content-type');
  res.setHeader('x-xsportsx-version',VERSION);
  res.setHeader('cache-control','no-store');
  res.setHeader('content-type',type);
}
function json(res,status,obj){const s=JSON.stringify(obj);headers(res);res.statusCode=status;res.setHeader('content-length',Buffer.byteLength(s));res.end(s)}
function encrypt(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',KEY,iv),b=Buffer.concat([c.update(JSON.stringify(v),'utf8'),c.final()]);return [iv,c.getAuthTag(),b].map(x=>x.toString('base64url')).join('.')}
function decrypt(t){try{const[a,b,c]=String(t||'').split('.');if(!a||!b||!c)return null;const d=crypto.createDecipheriv('aes-256-gcm',KEY,Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString())}catch{return null}}
function normalizeXtream(v){try{const u=new URL(String(v||'').trim());u.search='';u.hash='';u.pathname=u.pathname.replace(/\/+$/,'').replace(/\/player_api\.php$/i,'');return u.toString().replace(/\/$/,'')}catch{return''}}
function cacheGet(k){const x=CACHE.get(k);if(x&&x.exp>Date.now())return x.v;CACHE.delete(k);return null}
function cacheSet(k,v,ms){CACHE.set(k,{v,exp:Date.now()+ms});return v}
async function fetchText(u){const r=await fetch(u,{headers:{'user-agent':'XSportsX/9.6'},signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error('HTTP '+r.status);return r.text()}
async function getJson(u){const r=await fetch(u,{headers:{'user-agent':'XSportsX/9.6','accept':'application/json'},signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9+]+/g,' ').replace(/\s+/g,' ').trim()}
function tokens(s){return new Set(norm(s).split(' ').filter(x=>x.length>2))}
function isoDate(d=new Date()){return d.toISOString().slice(0,10)}
function eventKey(e){return `${norm(e.league)}|${norm(e.away)}|${norm(e.home)}|${Math.round(new Date(e.start).getTime()/60000)}`}
function validEvent(e){const t=Date.parse(e.start);if(!Number.isFinite(t))return false;const now=Date.now();if(e.status==='final'||e.status==='postponed'||e.status==='cancelled')return false;if(t<now-4*60*60*1000)return false;return t<now+8*24*60*60*1000}
function mergeEvents(list){const m=new Map();for(const e of list){if(!e||!validEvent(e))continue;const k=eventKey(e),old=m.get(k);if(!old)m.set(k,e);else{old.broadcasts=[...new Set([...(old.broadcasts||[]),...(e.broadcasts||[])])];old.sources=[...new Set([...(old.sources||[]),e.source])];if(old.status==='scheduled'&&e.status==='live')old.status='live';if(e.poster)old.poster=e.poster;}}return [...m.values()].sort((a,b)=>Date.parse(a.start)-Date.parse(b.start))}
function espnNormalize(id,e){const c=e.competitions?.[0],teams=c?.competitors||[];const away=teams.find(x=>x.homeAway==='away'),home=teams.find(x=>x.homeAway==='home');const status=c?.status?.type;return{league:id,source:'ESPN',sourceId:String(e.id),away:away?.team?.displayName||teams[0]?.team?.displayName||'Away',home:home?.team?.displayName||teams[1]?.team?.displayName||'Home',awayShort:away?.team?.abbreviation,homeShort:home?.team?.abbreviation,start:e.date,status:status?.completed?'final':/postponed/i.test(status?.name||'')?'postponed':status?.state==='in'?'live':'scheduled',broadcasts:(c?.broadcasts||[]).flatMap(x=>[x.names,x.market,x.type?.shortName,x.type?.longName]).flat().filter(Boolean)}}
async function espn(id){const l=LEAGUE(id);try{const d=await getJson(`https://site.api.espn.com/apis/site/v2/sports/${l[3]}/${l[4]}/scoreboard?limit=100`);return(Array.isArray(d.events)?d.events:[]).map(e=>espnNormalize(id,e))}catch{return[]}}
async function mlbOfficial(){try{const s=isoDate(new Date(Date.now()-6*60*60*1000)),e=isoDate(new Date(Date.now()+8*24*60*60*1000));const u=`https://statsapi.mlb.com/api/v1/schedule?sportId=1&startDate=${s}&endDate=${e}&hydrate=team,broadcasts`;const d=await getJson(u);return(d.dates||[]).flatMap(day=>(day.games||[]).map(g=>({league:'mlb',source:'MLB.com StatsAPI',sourceId:String(g.gamePk),away:g.teams?.away?.team?.name,home:g.teams?.home?.team?.name,awayShort:g.teams?.away?.team?.abbreviation,homeShort:g.teams?.home?.team?.abbreviation,start:g.gameDate,status:/final/i.test(g.status?.abstractGameState||'')?'final':/postponed|cancel/i.test(g.status?.detailedState||'')?'postponed':'scheduled',broadcasts:(g.broadcasts||[]).flatMap(b=>[b.name,b.callSign,b.network]).filter(Boolean)})))}catch{return[]}}
async function nhlOfficial(){try{const d=await getJson(`https://api-web.nhle.com/v1/schedule/now`);return(d.gameWeek||[]).flatMap(w=>(w.games||[]).map(g=>({league:'nhl',source:'NHL.com API',sourceId:String(g.id),away:g.awayTeam?.placeName?.default?`${g.awayTeam.placeName.default} ${g.awayTeam.commonName?.default||''}`.trim():g.awayTeam?.abbrev,home:g.homeTeam?.placeName?.default?`${g.homeTeam.placeName.default} ${g.homeTeam.commonName?.default||''}`.trim():g.homeTeam?.abbrev,awayShort:g.awayTeam?.abbrev,homeShort:g.homeTeam?.abbrev,start:g.startTime,status:/FINAL|OFFICIAL/i.test(g.gameState||'')?'final':/LIVE/i.test(g.gameState||'')?'live':'scheduled',broadcasts:(g.tvBroadcasts||[]).flatMap(b=>[b.network?.name,b.network?.id]).filter(Boolean)})))}catch{return[]}}
async function nbaOfficial(){try{const d=await getJson('https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json');return(d.scoreboard?.games||[]).map(g=>({league:'nba',source:'NBA.com',sourceId:String(g.gameId),away:g.awayTeam?.teamName||g.awayTeam?.teamTricode,home:g.homeTeam?.teamName||g.homeTeam?.teamTricode,awayShort:g.awayTeam?.teamTricode,homeShort:g.homeTeam?.teamTricode,start:g.gameTimeUTC,status:g.gameStatus===3?'final':g.gameStatus===2?'live':'scheduled',broadcasts:[]}))}catch{return[]}}
async function ufcOfficial(){try{const html=await fetchText('https://www.ufc.com/events');const out=[];const re=/(?:###\s*)?([A-Z][A-Za-z]+(?:\s+[A-Z][A-Za-z]+){0,3}\s+vs\s+[A-Z][A-Za-z]+(?:\s+[A-Z][A-Za-z]+){0,3})[\s\S]{0,900}?(Sat|Sun|Fri|Thu),\s+([A-Z][a-z]{2})\s+(\d{1,2})\s*\/\s*([0-9:]+)\s*([AP]M)\s+EDT[\s\S]{0,500}?Watch On (Paramount\+|ESPN\+|UFC Fight Pass)/gi;let m;while((m=re.exec(html))){const month={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11}[m[3]];const now=new Date(),year=now.getUTCFullYear();const start=new Date(Date.UTC(year,month,Number(m[4]),...m[5].split(':').map(Number)));if(m[6]==='PM'&&start.getUTCHours()<12)start.setUTCHours(start.getUTCHours()+12);out.push({league:'ufc',source:'UFC.com',sourceId:norm(m[1]),away:m[1].split(/\s+vs\s+/i)[0],home:m[1].split(/\s+vs\s+/i)[1],start:start.toISOString(),status:'scheduled',broadcasts:[m[7]]})}return out}catch{return[]}}
async function ncaaOfficial(){try{const html=await fetchText('https://www.ncaa.com/scoreboard/football/fbs');const out=[];const jsons=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];for(const x of jsons){try{const v=JSON.parse(x[1]);const arr=Array.isArray(v)?v:[v];for(const e of arr){if(e['@type']==='SportsEvent'&&e.startDate&&e.name)out.push({league:'ncaaf',source:'NCAA.com',sourceId:e.url||e.name,away:e.name.split(/\s+at\s+|\s+vs\.?\s+/i)[0],home:e.name.split(/\s+at\s+|\s+vs\.?\s+/i)[1]||e.name,start:e.startDate,status:'scheduled',broadcasts:e.broadcast?.name?[e.broadcast.name]:[]})}}catch{}}return out}catch{return[]}}
async function schedules(id){const k='events:'+id,x=cacheGet(k);if(x)return x;let all=[];if(id==='mlb')all.push(...await mlbOfficial());if(id==='nhl')all.push(...await nhlOfficial());if(id==='nba')all.push(...await nbaOfficial());if(id==='ufc')all.push(...await ufcOfficial());if(id==='ncaaf')all.push(...await ncaaOfficial());all.push(...await espn(id));const v=cacheSet(k,mergeEvents(all),20000);return v}
async function xtreamChannels(c){const k=`channels:${c.xtream.baseUrl}:${c.xtream.username}`,x=cacheGet(k);if(x)return x;try{const u=new URL('/player_api.php',c.xtream.baseUrl+'/');u.searchParams.set('username',c.xtream.username);u.searchParams.set('password',c.xtream.password);u.searchParams.set('action','get_live_streams');const d=await getJson(u);return cacheSet(k,Array.isArray(d)?d:[],30000)}catch{return[]}}
function eventNames(e){return[e.away,e.home,e.awayShort,e.homeShort].filter(Boolean)}
function eventMeta(id,e,base){const l=LEAGUE(id);return{id:`sports:${id}:event:${encodeURIComponent(e.sourceId||eventKey(e))}`,type:'tv',name:`${e.away} vs ${e.home}`,poster:`${base}/artwork.svg`,posterShape:'landscape',releaseInfo:new Date(e.start).toISOString().slice(0,10),description:`${e.status==='live'?'LIVE • ':''}${new Date(e.start).toLocaleString()} • ${l[1]} • ${[...(e.broadcasts||[])].slice(0,4).join(', ')}`,genres:[l[1]]}}
function channelScore(ch,id,e){const l=LEAGUE(id),text=norm([ch.name,ch.stream_display_name,ch.category_name,ch.group_title,ch.tvg_name,ch.epg_channel_id].join(' '));let score=0;for(const b of (e.broadcasts||[])){const x=norm(b);if(x&&text.includes(x))score+=140}for(const a of l[5]){const x=norm(a);if(x&&text.includes(x))score+=35}const words=new Set([...eventNames(e).flatMap(tokens)]);for(const w of words)if(tokens(text).has(w))score+=32;if(/local|regional|rsn|affiliate|network/.test(text))score+=6;return score}
function manifest(base,c){return{id:'community.xsportsx',version:VERSION,name:'XSportsX',description:'Multi-source live sports from your own Xtream/M3U source.',types:['tv'],resources:['catalog',{name:'meta',types:['tv'],idPrefixes:['sports:']},{name:'stream',types:['tv'],idPrefixes:['sports:']}],catalogs:c.sports.map(id=>{const l=LEAGUE(id);return{type:'tv',id,name:`${l[2]} ${l[1]}`,extra:[{name:'search',isRequired:false}]}}),behaviorHints:{configurable:false,configurationRequired:false},logo:`${base}/artwork.svg`}}
function artwork(res){headers(res,'image/svg+xml');res.end('<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="100%" height="100%" fill="#070b12"/><text x="50%" y="47%" text-anchor="middle" fill="white" font-family="Arial" font-size="64" font-weight="700">XSPORTSX</text><text x="50%" y="57%" text-anchor="middle" fill="#ff344b" font-family="Arial" font-size="26">MULTI-SOURCE SPORTS</text></svg>')}
function page(base){const cards=LEAGUES.map(([id,n,e])=>`<button class=l type=button data-id="${id}" aria-pressed=false>${e} <b>${n}</b></button>`).join('');return `<!doctype html><meta name=viewport content="width=device-width"><style>body{margin:0;background:#070b12;color:#fff;font:16px system-ui}main{max-width:700px;margin:auto;padding:20px}.p{background:#0d1420;border:1px solid #25344a;border-radius:18px;padding:20px;margin:14px 0}.l{display:block;width:100%;margin:7px 0;padding:15px;text-align:left;border-radius:14px;border:1px solid #2a3a50;background:#121b29;color:#fff;font-size:17px}.l[aria-pressed=true]{border-color:#ff344b;background:#26131a}.l[aria-pressed=true]:after{content:' ✓';float:right}.i{width:100%;padding:14px;margin:6px 0;box-sizing:border-box;background:#080e17;color:#fff;border:1px solid #304159;border-radius:10px}.go{width:100%;padding:16px;border:0;border-radius:14px;background:#e92840;color:#fff;font-weight:800;font-size:17px}.go:disabled{opacity:.4}.small{color:#9eacc0}</style><main><div class=p><h1>XSportsX</h1><div>Build ${VERSION} • multi-source schedules</div><p class=small>Schedules merge league-owned sources where available with ESPN as a backup. Pregame matching uses broadcast data plus the entire Xtream channel list.</p></div><div class=p><h2>Choose leagues</h2><div id=c>0 selected</div>${cards}</div><div class=p><h2>Xtream source</h2><form method=post action="${base}/configure"><input type=hidden name=sports id=s><input type=hidden name=source value=xtream><input class=i name=xtream placeholder="https://server.example.com" required><input class=i name=username placeholder=Username required><input class=i name=password type=password placeholder=Password required><button class=go id=g disabled>Create manifest</button></form></div></main><script>let b=[...document.querySelectorAll('.l')],c=document.querySelector('#c'),s=document.querySelector('#s'),g=document.querySelector('#g');function r(){let x=b.filter(q=>q.getAttribute('aria-pressed')==='true').map(q=>q.dataset.id);c.textContent=x.length+' selected';s.value=x.join(',');g.disabled=!x.length}b.forEach(q=>q.onclick=()=>{q.setAttribute('aria-pressed',q.getAttribute('aria-pressed')!=='true');r()});r()</script>`}
async function body(req){return new Promise((a,b)=>{let s='';req.on('data',x=>{s+=x;if(s.length>32768){req.destroy();b(Error('Request too large'))}});req.on('end',()=>a(s));req.on('error',b)})}
function parseBody(s){const p=new URLSearchParams(s);return Object.fromEntries(p.entries())}
async function catalog(c,id,base,search){let ev=await schedules(id);const q=norm(search);if(q)ev=ev.filter(e=>norm([e.away,e.home,e.awayShort,e.homeShort,e.broadcasts?.join(' ')].join(' ')).includes(q));return ev.slice(0,100).map(e=>eventMeta(id,e,base))}
async function streamsForEvent(c,id,rawId,base){const ev=await schedules(id);let decoded=decodeURIComponent(rawId);let e=ev.find(x=>String(x.sourceId)===decoded);if(!e){const n=decoded.split(':');const guess=norm(n.slice(-1)[0]);e=ev.find(x=>norm(`${x.away} ${x.home}`)===guess)}if(!e)return[];const ch=await xtreamChannels(c);const ranked=ch.map(x=>({x,s:channelScore(x,id,e)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,30);return ranked.map((r,i)=>{const x=r.x,sid=String(x.stream_id||x.id||x.num||''),token=encrypt({p:c,streamId:sid,exp:Date.now()+300000});return{name:`${x.name||x.stream_display_name||'Channel'}${i===0?' • Best match':''}`,title:`${LEAGUE(id)[1]} • ${x.name||x.stream_display_name||'Channel'}`,url:`${base}/${token}/play/${encodeURIComponent(sid)}`,behaviorHints:{notWebReady:true}}})}
async function streamChannel(c,sid){const ch=(await xtreamChannels(c)).find(x=>String(x.stream_id||x.id||x.num)===String(sid));if(!ch)return[];const u=new URL('/live/'+encodeURIComponent(c.xtream.username)+'/'+encodeURIComponent(c.xtream.password)+'/'+encodeURIComponent(sid)+'.ts',c.xtream.baseUrl+'/');return[{name:ch.name||'Channel',url:u.toString(),behaviorHints:{notWebReady:true}}]}
async function main(req,res){try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);const parts=u.pathname.split('/').filter(Boolean);if(req.method==='OPTIONS'){headers(res);res.statusCode=204;return res.end()}if(u.pathname==='/health'){return json(res,200,{ok:true,version:VERSION,sources:['ESPN','MLB.com StatsAPI','NHL.com API','NBA.com','UFC.com','NCAA.com'],time:new Date().toISOString()})}if(u.pathname==='/configure'&&req.method==='GET'){headers(res,'text/html; charset=utf-8');res.end(page(`${u.origin}`));return}if(u.pathname==='/configure'&&req.method==='POST'){const f=parseBody(await body(req));const sports=String(f.sports||'').split(',').filter(x=>VALID.has(x));const base=f.xtream?normalizeXtream(f.xtream):'';if(!sports.length||!base||!f.username||!f.password)return json(res,400,{error:'Invalid configuration'});const token=encrypt({sports,xtream:{baseUrl:base,username:String(f.username),password:String(f.password)}});const manifest=`${u.origin}/${token}/manifest.json`;headers(res,'text/html; charset=utf-8');res.end(`<!doctype html><meta name=viewport content="width=device-width"><style>body{margin:0;background:#070b12;color:#fff;font:16px system-ui;padding:28px}.box{max-width:720px;margin:auto;background:#0d1420;border:1px solid #29405b;border-radius:20px;padding:24px}a{color:#79b7ff;word-break:break-all}.ok{color:#5ff0a1;font-size:30px;font-weight:800}</style><div class=box><div class=ok>✓ Manifest Ready</div><p>XSportsX ${VERSION} private configuration created.</p><p><a href="${manifest}">Open manifest JSON</a></p><textarea style="width:100%;min-height:110px;background:#080e17;color:#fff;border:1px solid #304159;border-radius:10px;padding:12px;box-sizing:border-box">${manifest}</textarea><p>Install this manifest in Nuvio. Use this same manifest on your other devices.</p></div>`);return}
if(parts.length>=2){const token=parts[0],c=decrypt(token);if(!c)return json(res,404,{error:'Invalid configuration'});if(parts[1]==='manifest.json')return json(res,200,manifest(u.origin,c));if(parts[1]==='artwork.svg')return artwork(res);if(parts[1]==='catalog'&&parts[2]==='tv'&&parts[3]){const id=parts[3].replace(/\.json$/,'');if(!VALID.has(id))return json(res,404,{metas:[]});return json(res,200,{metas:await catalog(c,id,u.origin,u.searchParams.get('search')||'')})}if(parts[1]==='meta'&&parts[2]==='tv'&&parts[3]){const rid=parts[3].replace(/\.json$/,'');const id=rid.split(':')[1]||c.sports[0];const ev=await schedules(id);const e=ev.find(x=>String(x.sourceId)===decodeURIComponent(rid.split(':').slice(2).join(':')));return json(res,200,{meta:e?eventMeta(id,e,u.origin):null})}if(parts[1]==='stream'&&parts[2]==='tv'&&parts[3]){const rid=parts[3].replace(/\.json$/,'');const bits=rid.split(':');const id=bits[1];if(!VALID.has(id))return json(res,200,{streams:[]});const raw=bits.slice(2).join(':').replace(/^event:/,'');return json(res,200,{streams:await streamsForEvent(c,id,raw,u.origin)})}if(parts[1]==='play'&&parts[2]){const p=decrypt(token);if(!p||!p.p||!p.streamId||p.exp<Date.now())return json(res,403,{error:'Expired stream token'});const r=await streamChannel(p.p,p.streamId);if(!r.length)return json(res,404,{error:'Stream not found'});res.statusCode=302;res.setHeader('location',r[0].url);return res.end()}}
return json(res,404,{error:'Not found'})}catch(e){return json(res,500,{error:'XSportsX server error',detail:e.message})}}
http.createServer(main).listen(PORT,'0.0.0.0',()=>console.log(`XSportsX ${VERSION} listening on ${PORT}`));
