const http=require('http');
const crypto=require('crypto');
const {URL}=require('url');
const PORT=Number(process.env.PORT||10000);
const SECRET=process.env.XSPORTSX_CONFIG_SECRET||'change-this-in-render';
const KEY=crypto.createHash('sha256').update(SECRET).digest();
const VERSION='9.8.0',CACHE=new Map(),TIMEOUT=8000;
const LEAGUES=[
['nfl','NFL','🏈','football','nfl',['NFL','NFL Network','NFL RedZone','CBS','Paramount+','FOX','FOX One','NBC','Peacock','ESPN','ABC','Prime Video','Netflix']],
['ncaaf','NCAA Football','🏈','football','college-football',['ESPN','ESPN+','ESPN2','ESPNU','SEC Network','ACC Network','Big Ten Network','CBS','CBS Sports Network','FOX','FOX One','FS1','FS2','NBC','ABC','Peacock','TNT','TBS','truTV','The CW','FloSports','FanDuel Sports Network']],
['nba','NBA','🏀','basketball','nba',['ESPN','ESPN2','ABC','NBA TV','TNT','TBS','NBC','Peacock','Prime Video','Amazon Prime','FanDuel Sports Network','SportsNet','Spectrum SportsNet','YES','MSG']],
['wnba','WNBA','🏀','basketball','wnba',['ESPN','ESPN2','ABC','CBS','ION','NBA TV','Prime Video','Amazon Prime','CBS Sports Network']],
['ncaab','NCAA Basketball','🏀','basketball','mens-college-basketball',['ESPN','ESPN+','ESPN2','ESPNU','SEC Network','ACC Network','Big Ten Network','CBS','CBS Sports Network','FOX','FS1','FS2','TNT','TBS','truTV','NBC','Peacock','ABC']],
['mlb','MLB','⚾','baseball','mlb',['ESPN','ESPN2','FOX','FS1','FOX Deportes','TBS','MLB Network','NBC','NBC Sports','Peacock','Apple TV','Apple TV+','Netflix','FOX Sports','ABC','FanDuel Sports Network','SportsNet','YES','SNY','NESN','MASN','Marquee Sports Network','CHSN','Spectrum SportsNet','SportsNet LA','NBC Sports Bay Area','NBC Sports California','NBC Sports Chicago','NBC Sports Philadelphia','NBC Sports Boston','NBC Sports Washington','Bally','Altitude Sports','Space City Home Network','Rogers Sportsnet','Sportsnet+','MLB.TV']],
['nhl','NHL','🏒','hockey','nhl',['ESPN','ESPN+','TNT','TBS','ABC','Hulu','NHL Network','NBC','Peacock','SportsNet','TSN','TSN2','TSN 3','TSN 4','TSN 5','FanDuel Sports Network','NESN','SNY','MSG','YES','Altitude Sports','Victory+','CHSN','Root Sports']],
['mls','MLS','⚽','soccer','usa.1',['Apple TV','Apple TV+','FOX','FS1','FS2','FOX Deportes','ESPN','ESPN2','ABC','TNT','TBS','CBS','Paramount+','Peacock','Telemundo','Univision','TUDN']],
['epl','Premier League','⚽','soccer','eng.1',['NBC','Peacock','USA Network','NBC Sports','Telemundo','Universo','Sky Sports','TNT Sports','ESPN','ESPN+']],
['ucl','UEFA Champions League','⚽','soccer','uefa.champions',['Paramount+','CBS','TNT Sports','TNT','TBS','Univision','TUDN','DAZN','ESPN','ESPN+','beIN Sports']],
['laliga','LaLiga','⚽','soccer','esp.1',['ESPN','ESPN+','ESPN Deportes','ABC','ESPN2','DAZN','beIN Sports']],
['seriea','Serie A','⚽','soccer','ita.1',['CBS','Paramount+','TUDN','Univision','DAZN','ESPN+']],
['bundesliga','Bundesliga','⚽','soccer','ger.1',['ESPN','ESPN+','ESPN Deportes','DAZN','Sky Sports']],
['ligue1','Ligue 1','⚽','soccer','fra.1',['beIN Sports','beIN Sports en Español','DAZN','ESPN+','TNT Sports']],
['ufc','UFC','🥊','mma','ufc',['Paramount+','CBS','TSN','TSN2','TSN 3','TSN 4','TSN 5','ESPN','ESPN+','TNT Sports','Sportsnet','UFC Fight Pass']],
['boxing','Boxing','🥊','boxing','boxing',['DAZN','ESPN','ESPN+','Prime Video','Amazon Prime','PBC','FOX','FOX One','CBS','Paramount+','TNT Sports','TNT','TBS','Top Rank','ESPN Deportes','TSN','TSN2']]
];
const VALID=new Set(LEAGUES.map(x=>x[0])),L=id=>LEAGUES.find(x=>x[0]===id);
function norm(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9+]+/g,' ').replace(/\s+/g,' ').trim()}
function words(s){return [...new Set(norm(s).split(' ').filter(x=>x.length>2))]}
function cached(k){const x=CACHE.get(k);return x&&x.exp>Date.now()?x.v:null}
function put(k,v,ms){CACHE.set(k,{v,exp:Date.now()+ms});return v}
function hdr(r,t='application/json; charset=utf-8'){r.setHeader('access-control-allow-origin','*');r.setHeader('access-control-allow-methods','GET,POST,OPTIONS');r.setHeader('access-control-allow-headers','content-type');r.setHeader('cache-control','no-store');r.setHeader('x-xsportsx-version',VERSION);r.setHeader('content-type',t)}
function json(r,s,o){hdr(r);r.statusCode=s;r.end(JSON.stringify(o))}
function enc(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',KEY,iv),b=Buffer.concat([c.update(JSON.stringify(v),'utf8'),c.final()]);return[iv,c.getAuthTag(),b].map(x=>x.toString('base64url')).join('.')}
function dec(t){try{const[a,b,c]=String(t||'').split('.');if(!a||!b||!c)return null;const d=crypto.createDecipheriv('aes-256-gcm',KEY,Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString())}catch{return null}}
async function get(u,timeout=TIMEOUT){const r=await fetch(u,{headers:{'user-agent':`XSportsX/${VERSION}`,'accept':'application/json'},signal:AbortSignal.timeout(timeout)});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function text(u,timeout=TIMEOUT){const r=await fetch(u,{headers:{'user-agent':`XSportsX/${VERSION}`},signal:AbortSignal.timeout(timeout)});if(!r.ok)throw Error('HTTP '+r.status);return r.text()}
function espnNorm(id,e){const c=e.competitions?.[0],t=c?.competitors||[],a=t.find(x=>x.homeAway==='away'),h=t.find(x=>x.homeAway==='home'),s=c?.status?.type||{};return{league:id,source:'ESPN',sourceId:String(e.id),away:a?.team?.displayName||t[0]?.team?.displayName,home:h?.team?.displayName||t[1]?.team?.displayName,start:e.date,status:s.completed?'final':/postponed|cancel/i.test(s.name||'')?'postponed':s.state==='in'?'live':'scheduled',broadcasts:(c?.broadcasts||[]).flatMap(x=>[...(x.names||[]),x.market,x.type?.shortName,x.type?.longName]).filter(Boolean)}}
async function espn(id){const l=L(id);if(!l)return[];try{const d=await get(`https://site.api.espn.com/apis/site/v2/sports/${l[3]}/${l[4]}/scoreboard?limit=100`);return(d.events||[]).map(e=>espnNorm(id,e))}catch{return[]}}
async function official(id){try{
if(id==='mlb'){const a=new Date(Date.now()-86400000).toISOString().slice(0,10),b=new Date(Date.now()+14*86400000).toISOString().slice(0,10);const d=await get(`https://statsapi.mlb.com/api/v1/schedule?sportId=1&startDate=${a}&endDate=${b}&hydrate=team,broadcasts`);return(d.dates||[]).flatMap(x=>(x.games||[]).map(g=>({league:id,source:'MLB.com',sourceId:String(g.gamePk),away:g.teams?.away?.team?.name,home:g.teams?.home?.team?.name,start:g.gameDate,status:/final/i.test(g.status?.abstractGameState||'')?'final':/postponed|cancel/i.test(g.status?.detailedState||'')?'postponed':'scheduled',broadcasts:(g.broadcasts||[]).flatMap(b=>[b.name,b.callSign,b.network,b.type]).filter(Boolean)})))}
if(id==='nba'){const d=await get('https://cdn.nba.com/static/json/liveData/scoreboard/todaysScoreboard_00.json');return(d.scoreboard?.games||[]).map(g=>({league:id,source:'NBA.com',sourceId:String(g.gameId),away:g.awayTeam?.teamName||g.awayTeam?.teamTricode,home:g.homeTeam?.teamName||g.homeTeam?.teamTricode,start:g.gameTimeUTC,status:g.gameStatus===3?'final':g.gameStatus===2?'live':'scheduled',broadcasts:[]}))}
if(id==='nhl'){const d=await get('https://api-web.nhle.com/v1/schedule/now');return(d.gameWeek||[]).flatMap(w=>(w.games||[]).map(g=>({league:id,source:'NHL.com',sourceId:String(g.id),away:g.awayTeam?.placeName?.default?`${g.awayTeam.placeName.default} ${g.awayTeam.commonName?.default||''}`.trim():g.awayTeam?.abbrev,home:g.homeTeam?.placeName?.default?`${g.homeTeam.placeName.default} ${g.homeTeam.commonName?.default||''}`.trim():g.homeTeam?.abbrev,start:g.startTime,status:/FINAL|OFFICIAL/i.test(g.gameState||'')?'final':'scheduled',broadcasts:(g.tvBroadcasts||[]).flatMap(b=>[b.network?.name,b.network?.id]).filter(Boolean)})))}
if(id==='ufc'){try{const d=await get('https://site.api.espn.com/apis/site/v2/sports/mma/ufc/scoreboard?limit=100');if(d.events?.length)return d.events.map(e=>espnNorm(id,e))}catch{}const h=await text('https://www.ufc.com/events',7000),o=[],r=/([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){0,3})\s+(?:vs\.?|v\.)\s+([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){0,3})/g;let m;while((m=r.exec(h))&&o.length<30)o.push({league:id,source:'UFC.com',sourceId:`${norm(m[1])}-${norm(m[2])}`,away:m[1],home:m[2],start:null,status:'scheduled',broadcasts:[]});return o}
return[];
}catch{return[]}}
function valid(e){const t=Date.parse(e.start);return Boolean(e.away&&e.home&&Number.isFinite(t)&&t>=Date.now()-6*3600000&&t<=Date.now()+14*86400000&&!/^(final|postponed|cancelled|canceled)$/i.test(e.status||''))}
async function events(id){const k='events:'+id,o=cached(k);if(o)return o;const[a,b]=await Promise.all([official(id),espn(id)]),m=new Map();for(const e of[...a,...b].filter(valid)){const q=`${norm(e.away)}|${norm(e.home)}|${Math.round(Date.parse(e.start)/60000)}`,p=m.get(q);if(!p)m.set(q,{...e,broadcasts:[...new Set(e.broadcasts||[])]});else p.broadcasts=[...new Set([...(p.broadcasts||[]),...(e.broadcasts||[])])]}return put(k,[...m.values()].sort((x,y)=>Date.parse(x.start)-Date.parse(y.start)),20000)}
async function live(c){const k=`live:${c.xtream.baseUrl}:${c.xtream.username}`,o=cached(k);if(o)return o;try{const u=new URL('/player_api.php',c.xtream.baseUrl.replace(/\/+$/,'')+'/');u.searchParams.set('username',c.xtream.username);u.searchParams.set('password',c.xtream.password);u.searchParams.set('action','get_live_streams');const d=await get(u.toString(),10000);return put(k,Array.isArray(d)?d:[],30000)}catch{return[]}}
async function epg(c,ch){const id=ch.epg_channel_id||ch.stream_id,k=`epg:${c.xtream.baseUrl}:${c.xtream.username}:${id}`,o=cached(k);if(o)return o;try{const u=new URL('/player_api.php',c.xtream.baseUrl.replace(/\/+$/,'')+'/');u.searchParams.set('username',c.xtream.username);u.searchParams.set('password',c.xtream.password);u.searchParams.set('action','get_short_epg');u.searchParams.set('stream_id',String(ch.stream_id));u.searchParams.set('limit','10');const d=await get(u.toString(),5000),x=d.epg_listings||d||[];return put(k,Array.isArray(x)?x:[],15000)}catch{return[]}}
const ALIASES={'paramount+':['paramount plus','paramount'],'fox':['fox network','fox sports','fox one'],'fs1':['fox sports 1'],'fs2':['fox sports 2'],'cbs':['cbs sports','cbs network'],'abc':['abc network'],'nbc':['nbc sports','nbc network'],'espn':['espn network'],'espn+':['espn plus'],'tnt':['tnt sports'],'tbs':['tbs sports'],'tsn':['tsn1','tsn 1','tsn2','tsn 2','tsn3','tsn 3','tsn4','tsn 4','tsn5','tsn 5'],'sportsnet':['sports net','sportsnet+','sportsnet plus'],'mlb network':['mlb tv'],'nba tv':['nba television'],'nhl network':['nhl tv'],'usa network':['usa'],'peacock':['peacock tv'],'prime video':['amazon prime','amazon prime video'],'fan duel sports network':['fanduel','fdsn'],'bally':['bally sports'],'victory+':['victory plus'],'the cw':['cw'],'be in sports':['bein sports','beinsports'],'ufc fight pass':['ufc pass']};
function aliases(v){const n=norm(v),o=new Set([n]);for(const[k,a]of Object.entries(ALIASES))if(n===k||a.some(x=>n===norm(x))){o.add(norm(k));a.forEach(x=>o.add(norm(x)))}return[...o].filter(Boolean)}
function ctext(c){return norm([c.name,c.stream_display_name,c.category_name,c.group_title,c.tvg_name,c.epg_channel_id].join(' '))}
function teamScore(s,t){const n=norm(t);let x=s.includes(n)?55:0;for(const w of words(n))if(w.length>3&&s.includes(w))x+=16;return x}
function baseScore(c,id,e){const s=ctext(c);let n=teamScore(s,e.away)+teamScore(s,e.home);for(const b of e.broadcasts||[])for(const a of aliases(b))if(s.includes(a))n+=150;for(const b of L(id)?.[5]||[])for(const a of aliases(b))if(s.includes(a))n+=32;if(/local|regional|rsn|affiliate|sports network/.test(s))n+=8;return n}
function ptext(p){return norm([p.title,p.programme,p.program,p.description].join(' '))}
async function ranked(c,id,e){const all=await live(c);const cand=all.map(ch=>({ch,score:baseScore(ch,id,e)})).filter(x=>x.score>=25).sort((a,b)=>b.score-a.score).slice(0,80);const out=await Promise.all(cand.map(async x=>{let s=x.score;for(const p of await epg(c,x.ch)){const t=ptext(p);if(teamScore(t,e.away))s+=90;if(teamScore(t,e.home))s+=90;if((e.broadcasts||[]).some(b=>aliases(b).some(a=>t.includes(a))))s+=80;const pt=Date.parse(p.start||p.start_timestamp||p.start_time),et=Date.parse(p.end||p.end_timestamp||p.end_time),st=Date.parse(e.start);if(Number.isFinite(pt)&&Number.isFinite(st)&&Math.abs(pt-st)<3*3600000)s+=50;if(Number.isFinite(pt)&&Number.isFinite(et)&&Number.isFinite(st)&&st>=pt-1800000&&st<=et+1800000)s+=40}return{...x,score:s}}));return out.sort((a,b)=>b.score-a.score).slice(0,15)}
function streamUrl(c,ch){const base=c.xtream.baseUrl.replace(/\/+$/,'');const ext=String(ch.container_extension||'ts').replace(/[^a-z0-9]/gi,'')||'ts';return`${base}/live/${encodeURIComponent(c.xtream.username)}/${encodeURIComponent(c.xtream.password)}/${ch.stream_id}.${ext}`}
function eid(id,e){return`sports:${id}:event:${encodeURIComponent(String(e.sourceId))}`}
function meta(id,e,b){const l=L(id);return{id:eid(id,e),type:'tv',name:`${e.away} vs ${e.home}`,poster:`${b}/artwork.svg`,posterShape:'landscape',releaseInfo:new Date(e.start).toISOString().slice(0,10),description:`${e.status==='live'?'🔴 LIVE • ':''}${new Date(e.start).toLocaleString()} • ${l[1]}${e.broadcasts?.length?' • '+[...new Set(e.broadcasts)].slice(0,6).join(', '):''}`,genres:[l[1]]}}
function placeholder(id,b,ev){const l=L(id),n=ev[0];return{id:`sports:${id}:schedule`,type:'tv',name:n?`${l[1]} — Next: ${n.away} vs ${n.home}`:`${l[1]} — Schedule`,poster:`${b}/artwork.svg`,posterShape:'landscape',description:n?`Upcoming • ${new Date(n.start).toLocaleString()} • ${l[1]}`:`No games currently scheduled.`,genres:[l[1]]}}
function manifest(base){return{id:'community.xsportsx',version:VERSION,name:'XSportsX',description:'Fast multi-source sports schedules with Xtream channel and EPG matching.',types:['tv'],resources:['catalog',{name:'meta',types:['tv'],idPrefixes:['sports:']},{name:'stream',types:['tv'],idPrefixes:['sports:']}],catalogs:LEAGUES.map(([id,n,e])=>({type:'tv',id,name:`${e} ${n}`,extra:[{name:'search',isRequired:false}],showInHome:true})),behaviorHints:{configurable:false,configurationRequired:false},logo:`${base}/artwork.svg`}}
function page(base){const c=LEAGUES.map(([id,n,e])=>`<label><input type=checkbox name=sports value="${id}" checked> ${e} ${n}</label>`).join('');return`<!doctype html><meta name=viewport content="width=device-width"><style>body{background:#070b12;color:#fff;font:16px system-ui;padding:20px}main{max-width:700px;margin:auto}.box{background:#0d1420;border:1px solid #26364d;border-radius:18px;padding:20px;margin:14px 0}label,input,button{display:block;width:100%;box-sizing:border-box;margin:8px 0;padding:13px;border-radius:10px}label{background:#101a29}input{background:#080e17;color:white;border:1px solid #304159}button{background:#ff2d49;color:white;border:0;font-weight:800;font-size:17px}</style><main><div class=box><h1>XSportsX</h1><b>Build ${VERSION}</b><p>Official schedules + ESPN fallback + Xtream-wide channel/EPG matching.</p></div><form method=post action="${base}/configure"><div class=box><h2>Sports catalogs</h2>${c}</div><div class=box><h2>Xtream / M3U</h2><input name=xtream placeholder="https://your-server.example.com" required><input name=username placeholder="Username" required><input type=password name=password placeholder="Password" required><button>Create Private XSportsX Connection</button></div></form></main>`}
function body(req){return new Promise(ok=>{let b='';req.on('data',x=>b+=x);req.on('end',()=>ok(Object.fromEntries(new URLSearchParams(b).entries())))})}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){hdr(res);res.statusCode=204;return res.end()}const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;
if(p==='/health')return json(res,200,{ok:true,version:VERSION,catalogs:16});
if(p.endsWith('/artwork.svg')){hdr(res,'image/svg+xml');return res.end('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#070b12"/><text x="600" y="300" text-anchor="middle" fill="white" font-family="Arial" font-size="88" font-weight="800">XSPORTSX</text><text x="600" y="390" text-anchor="middle" fill="#ff2d49" font-family="Arial" font-size="38">LIVE SPORTS</text></svg>')}
if(p==='/configure'&&req.method==='GET'){hdr(res,'text/html; charset=utf-8');return res.end(page(u.origin))}
if(p==='/configure'&&req.method==='POST'){const f=await body(req),base=String(f.xtream||'').trim().replace(/\/+$/,'');if(!/^https?:\/\//i.test(base)||!f.username||!f.password)return json(res,400,{error:'Xtream server, username and password are required'});const token=enc({xtream:{baseUrl:base,username:String(f.username),password:String(f.password)},sports:LEAGUES.map(x=>x[0]),created:Date.now()});const install=`${u.origin}/s/${token}/manifest.json`;hdr(res,'text/html; charset=utf-8');return res.end(`<h1>XSportsX ${VERSION} Ready</h1><p>Private install URL:</p><p><a href="${install}">${install}</a></p>`)}
let a=p.split('/').filter(Boolean),token=null;if(a[0]==='s'||a[0]==='config'){token=a[1];a=a.slice(2)}else if(a[0]&&!['manifest.json','health'].includes(a[0])){token=a[0];a=a.slice(1)}
if(!token&&p==='/manifest.json')return json(res,200,manifest(u.origin));const cfg=token?dec(token):null;if(!cfg?.xtream)return json(res,400,{error:'Invalid XSportsX configuration',version:VERSION});
if(a.length===0||a[0]==='manifest.json')return json(res,200,manifest(u.origin));
if(a[0]==='catalog'&&a[1]&&a[2]){const id=decodeURIComponent(a[2].replace(/\.json$/,''));if(a[1]!=='tv'||!VALID.has(id))return json(res,200,{metas:[]});const ev=await events(id),metas=ev.slice(0,60).map(e=>meta(id,e,u.origin));if(!metas.length)metas.push(placeholder(id,u.origin,ev));return json(res,200,{metas})}
if(a[0]==='meta'&&a[1]&&a[2]){const raw=decodeURIComponent(a.slice(2).join('/')).replace(/\.json$/,'');if(raw.endsWith(':schedule')){const id=raw.split(':')[1];return json(res,200,{meta:placeholder(id,u.origin,await events(id))})}const m=raw.match(/^sports:([^:]+):event:(.+)$/);if(!m||!VALID.has(m[1]))return json(res,200,{meta:null});const ev=(await events(m[1])).find(e=>String(e.sourceId)===decodeURIComponent(m[2]));return json(res,200,{meta:ev?meta(m[1],ev,u.origin):null})}
if(a[0]==='stream'&&a[1]&&a[2]){const raw=decodeURIComponent(a.slice(2).join('/')).replace(/\.json$/,'');const m=raw.match(/^sports:([^:]+):event:(.+)$/);if(!m||!VALID.has(m[1]))return json(res,200,{streams:[]});const ev=(await events(m[1])).find(e=>String(e.sourceId)===decodeURIComponent(m[2]));if(!ev)return json(res,200,{streams:[]});const rs=await ranked(cfg,m[1],ev);return json(res,200,{streams:rs.map((x,i)=>({name:i?'XSportsX • '+(x.ch.name||x.ch.stream_display_name||'Channel'):'XSportsX • Best Match',title:`${ev.away} vs ${ev.home}${ev.status==='live'?' • LIVE':''}`,url:streamUrl(cfg,x.ch),behaviorHints:{bingeGroup:`xsportsx-${m[1]}-${x.ch.stream_id}`}}))})}
return json(res,404,{error:'Not found',version:VERSION})}catch(e){return json(res,500,{error:'XSportsX request failed',version:VERSION})}});
server.listen(PORT,()=>console.log(`XSportsX ${VERSION} listening on ${PORT}`));
