const THEMES={nfl:['NFL','#e31837','FOOTBALL'],ncaaf:['NCAA FOOTBALL','#39a7ff','COLLEGE FOOTBALL'],nba:['NBA','#ff4b2f','BASKETBALL'],wnba:['WNBA','#ff7a18','WOMEN’S BASKETBALL'],ncaab:['NCAA BASKETBALL','#39a7ff','COLLEGE BASKETBALL'],mlb:['MLB','#2aa7ff','BASEBALL'],nhl:['NHL','#d8e1eb','ICE HOCKEY'],mls:['MLS','#35e38a','SOCCER'],epl:['PREMIER LEAGUE','#9b55ff','ENGLISH FOOTBALL'],ucl:['CHAMPIONS LEAGUE','#35a7ff','EUROPEAN FOOTBALL'],laliga:['LALIGA','#ff4b3d','SPANISH FOOTBALL'],seriea:['SERIE A','#31a8ff','ITALIAN FOOTBALL'],bundesliga:['BUNDESLIGA','#ff3045','GERMAN FOOTBALL'],ligue1:['LIGUE 1','#baff00','FRENCH FOOTBALL'],ufc:['UFC','#ff1738','FIGHT NIGHT'],boxing:['BOXING','#ff1738','COMBAT SPORTS'],other:['OTHER SPORTS','#ff9d1b','LIVE SPORTS']};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const trunc=(v,n=28)=>{const s=String(v||'').trim();return s.length>n?s.slice(0,n-1)+'…':s};
function shellDefs(a){return `<defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#02040a"/><stop offset=".5" stop-color="#0c1728"/><stop offset="1" stop-color="#020307"/></linearGradient><linearGradient id="edge" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${a}"/><stop offset=".5" stop-color="#fff" stop-opacity=".22"/><stop offset="1" stop-color="${a}"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="18"/></filter></defs>`}
function brand(a){return `<text x="42" y="45" fill="#fff" font-family="Arial,sans-serif" font-size="24" font-style="italic" font-weight="900" letter-spacing="2"><tspan fill="${a}">X</tspan>SPORTS<tspan fill="${a}">X</tspan></text>`}
function artworkSvg(id){const [name,a,sub]=THEMES[id]||THEMES.other;return `<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 562">${shellDefs(a)}<rect width="1000" height="562" rx="26" fill="url(#bg)"/><circle cx="120" cy="510" r="220" fill="${a}" opacity=".16" filter="url(#glow)"/><circle cx="900" cy="70" r="190" fill="${a}" opacity=".12" filter="url(#glow)"/><rect x="5" y="5" width="990" height="552" rx="23" fill="none" stroke="url(#edge)" stroke-width="4"/>${brand(a)}<text x="500" y="270" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="60" font-style="italic" font-weight="900">${esc(name)}</text><text x="500" y="318" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="16" font-weight="900" letter-spacing="6">${esc(sub)}</text><path d="M120 370H880" stroke="${a}" stroke-width="3" opacity=".8"/><text x="500" y="414" text-anchor="middle" fill="#fff" opacity=".8" font-family="Arial,sans-serif" font-size="12" font-weight="900" letter-spacing="5">XSportsX • GAME CENTER</text></svg>`}
function eventArtworkSvg(league,away,home,state='pre',start='',awayLogo='',homeLogo='',awayShort='',homeShort='',eventName='',eventLogo=''){
 const [lname,a,sub]=THEMES[league]||THEMES.other;const live=state==='in',post=state==='post';const when=live?'LIVE':post?'FINAL':start?new Date(start).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'UPCOMING';
 const img=v=>v?`<image href="${String(v).replace(/&/g,'&amp;').replace(/"/g,'%22')}" preserveAspectRatio="xMidYMid meet"/>`:'';
 if(league==='ufc'||league==='boxing'){
  const title=trunc(eventName||away||lname,42);const detail=eventName?'OFFICIAL EVENT':'COMBAT SPORTS';
  const eventImg=eventLogo?`<image href="${String(eventLogo).replace(/&/g,'&amp;').replace(/"/g,'%22')}" x="330" y="105" width="340" height="150" preserveAspectRatio="xMidYMid meet"/>`:'';
  return `<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 562">${shellDefs(a)}<rect width="1000" height="562" rx="26" fill="url(#bg)"/><circle cx="160" cy="120" r="230" fill="${a}" opacity=".16" filter="url(#glow)"/><circle cx="850" cy="460" r="250" fill="${a}" opacity=".13" filter="url(#glow)"/><rect x="5" y="5" width="990" height="552" rx="23" fill="none" stroke="url(#edge)" stroke-width="4"/>${brand(a)}<text x="500" y="82" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="18" font-weight="900" letter-spacing="7">${esc(lname)} • ${esc(when)}</text>${eventImg}<text x="500" y="290" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="42" font-style="italic" font-weight="900">${esc(title)}</text><path d="M190 330H810" stroke="${a}" stroke-width="4"/><text x="500" y="380" text-anchor="middle" fill="#fff" opacity=".78" font-family="Arial,sans-serif" font-size="14" font-weight="900" letter-spacing="5">${detail}</text><rect x="350" y="425" width="300" height="38" rx="19" fill="${a}" opacity=".16" stroke="${a}"/><text x="500" y="450" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="11" font-weight="900" letter-spacing="3">STREAMS READY • XSPORTSX</text></svg>`;
 }
 const A=trunc(away||'AWAY'),H=trunc(home||'HOME');const safeShortA=trunc(awayShort||A,6),safeShortH=trunc(homeShort||H,6);const initials=(s)=>s.split(/\s+/).filter(Boolean).slice(0,3).map(x=>x[0]).join('').toUpperCase();
 const logo=(data,x)=>data?`<image href="${String(data).replace(/&/g,'&amp;').replace(/"/g,'%22')}" x="${x-54}" y="122" width="108" height="108" preserveAspectRatio="xMidYMid meet"/>`:'';
 const side=(x,name,short,data,label)=>`<g><rect x="${x-190}" y="115" width="380" height="190" rx="24" fill="#07101d" stroke="${a}" stroke-opacity=".5" stroke-width="2"/>${logo(data,x)}${!data?`<text x="${x}" y="190" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="34" font-weight="900">${esc(initials(name)||short)}</text>`:''}<text x="${x}" y="255" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="25" font-weight="900">${esc(name)}</text><text x="${x}" y="284" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="10" font-weight="900" letter-spacing="4">${label}</text></g>`;
 return `<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 562">${shellDefs(a)}<rect width="1000" height="562" rx="26" fill="url(#bg)"/><circle cx="90" cy="500" r="230" fill="${a}" opacity=".12" filter="url(#glow)"/><circle cx="910" cy="70" r="220" fill="${a}" opacity=".10" filter="url(#glow)"/><rect x="5" y="5" width="990" height="552" rx="23" fill="none" stroke="url(#edge)" stroke-width="4"/>${brand(a)}<text x="500" y="65" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="12" font-weight="900" letter-spacing="4">${esc(lname)} • ${esc(when)}</text>${side(245,A,safeShortA,awayLogo,'AWAY')}${side(755,H,safeShortH,homeLogo,'HOME')}<circle cx="500" cy="210" r="52" fill="#03060b" stroke="${a}" stroke-width="4"/><text x="500" y="220" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="24" font-style="italic" font-weight="900">VS</text><rect x="285" y="365" width="430" height="44" rx="22" fill="${a}" opacity=".12" stroke="${a}" stroke-opacity=".65"/><text x="500" y="393" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="11" font-weight="900" letter-spacing="3">${live?'● LIVE • STREAMS READY':post?'FINAL • STREAMS READY':'STREAMS READY'}</text><text x="500" y="475" text-anchor="middle" fill="#fff" opacity=".35" font-family="Arial,sans-serif" font-size="10" font-weight="900" letter-spacing="5">XSportsX • GAME CENTER</text></svg>`;
}
module.exports={THEMES,artworkSvg,eventArtworkSvg};