const THEMES={nfl:['NFL','#e31837','FOOTBALL'],ncaaf:['NCAA FOOTBALL','#39a7ff','COLLEGE FOOTBALL'],nba:['NBA','#ff4b2f','BASKETBALL'],wnba:['WNBA','#ff7a18','WOMEN’S BASKETBALL'],ncaab:['NCAA BASKETBALL','#39a7ff','COLLEGE BASKETBALL'],mlb:['MLB','#2aa7ff','BASEBALL'],nhl:['NHL','#d8e1eb','ICE HOCKEY'],mls:['MLS','#35e38a','SOCCER'],epl:['PREMIER LEAGUE','#9b55ff','ENGLISH FOOTBALL'],ucl:['CHAMPIONS LEAGUE','#35a7ff','EUROPEAN FOOTBALL'],laliga:['LALIGA','#ff4b3d','SPANISH FOOTBALL'],seriea:['SERIE A','#31a8ff','ITALIAN FOOTBALL'],bundesliga:['BUNDESLIGA','#ff3045','GERMAN FOOTBALL'],ligue1:['LIGUE 1','#baff00','FRENCH FOOTBALL'],ufc:['UFC','#ff1738','FIGHT NIGHT'],boxing:['BOXING','#ff1738','COMBAT SPORTS'],f1:['FORMULA 1','#e10600','MOTORSPORT'],nascar:['NASCAR','#e10600','MOTORSPORT'],dtm:['DTM','#e10600','MOTORSPORT'],motogp:['MOTOGP','#e10600','MOTORSPORT'],wrc:['WRC','#00a651','RALLY'],wec:['WEC','#1d5ca8','ENDURANCE'],formulae:['FORMULA E','#00a9e0','MOTORSPORT'],mxgp:['MXGP','#ff6a00','MOTOCROSS'],monsterjam:['MONSTER JAM','#f2c300','MOTORSPORT'],rugby:['RUGBY','#e30613','RUGBY'],volleyball:['VOLLEYBALL','#1b75bb','VOLLEYBALL'],lacrosse:['LACROSSE','#00a651','LACROSSE'],wrestling:['WRESTLING','#222','#WRESTLING'],wwe:['WWE','#d71920','WRESTLING'],soccer:['SOCCER','#35e38a','FOOTBALL'],other:['OTHER SPORTS','#ff9d1b','LIVE SPORTS']};
const NETWORKS={
 espn:['ESPN','#d71920','E'],espn2:['ESPN2','#d71920','E2'],espnu:['ESPNU','#d71920','EU'],espnews:['ESPN NEWS','#d71920','EN'],
 sec:['SEC NETWORK','#17365d','SEC'],acc:['ACC NETWORK','#0879c9','ACC'],bigten:['BIG TEN NETWORK','#10243e','B1G'],
 nflnetwork:['NFL NETWORK','#006db7','NFL'],fs1:['FS1','#0877bd','FS1'],fs2:['FS2','#0877bd','FS2'],foxsports:['FOX SPORTS','#0b67b2','FOX'],
 cbs:['CBS SPORTS','#1c5b8f','CBS'],nbcsports:['NBC SPORTS','#0088ce','NBC'],tnt:['TNT SPORTS','#171717','TNT'],tbs:['TBS SPORTS','#1477b8','TBS'],
 nbatev:['NBA TV','#e31837','NBA TV'],mlbnetwork:['MLB NETWORK','#0b4f8a','MLB'],nhlnetwork:['NHL NETWORK','#111','#NHL'],
 ufcpass:['UFC FIGHT PASS','#d20a0a','UFC'],paramount:['PARAMOUNT+','#0064ff','P+'],peacock:['PEACOCK','#111','#'],dazn:['DAZN','#111','DAZN'],
 redbull:['RED BULL TV','#111','RB'],monsterjam:['MONSTER JAM','#f2c300','MJ'],rugbypass:['RUGBYPASS TV','#e30613','RP'],
 stadium:['STADIUM','#111','ST'],fanduel:['FANDUEL','#138b44','FD'],thecw:['THE CW','#111','CW'],
 network:['NETWORK','#243247','TV']
};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const trunc=(v,n=28)=>{const s=String(v||'').trim();return s.length>n?s.slice(0,n-1)+'…':s};
const norm=v=>String(v??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function shellDefs(a){return `<defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#02040a"/><stop offset=".5" stop-color="#0c1728"/><stop offset="1" stop-color="#020307"/></linearGradient><linearGradient id="edge" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${a}"/><stop offset=".5" stop-color="#fff" stop-opacity=".22"/><stop offset="1" stop-color="${a}"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="18"/></filter></defs>`}
function brand(a){return `<text x="42" y="45" fill="#fff" font-family="Arial,sans-serif" font-size="24" font-style="italic" font-weight="900" letter-spacing="2"><tspan fill="${a}">X</tspan>SPORTS<tspan fill="${a}">X</tspan></text>`}
function badge(title,color,mark=title){const t=esc(mark);return `<rect x="350" y="112" width="300" height="220" rx="34" fill="#07101d" stroke="${color}" stroke-width="4"/><rect x="382" y="144" width="236" height="156" rx="24" fill="${color}"/><text x="500" y="238" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="${t.length>5?34:48}" font-style="italic" font-weight="900">${t}</text><text x="500" y="372" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="22" font-weight="900">${esc(title)}</text>`}
function logoSvg(map,id){const [title,color,mark]=map[id]||map.network;return `<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 562">${shellDefs(color)}<rect width="1000" height="562" rx="26" fill="url(#bg)"/>${brand(color)}${badge(title,color,mark)}<text x="500" y="432" text-anchor="middle" fill="${color}" font-family="Arial,sans-serif" font-size="13" font-weight="900" letter-spacing="5">HARDCODED • OFFLINE SAFE</text></svg>`}
function networkKey(name,group=''){const s=norm(`${name} ${group}`);if(/espn\s*2/.test(s))return'espn2';if(/espn\s*u/.test(s))return'espnu';if(/espn\s*news|espnews/.test(s))return'espnews';if(/\bespn\b/.test(s))return'espn';if(/sec\s*(network|n)/.test(s))return'sec';if(/acc\s*(network|n)/.test(s))return'acc';if(/big\s*ten|btn/.test(s))return'bigten';if(/nfl\s*network|nflnet/.test(s))return'nflnetwork';if(/fs1/.test(s))return'fs1';if(/fs2/.test(s))return'fs2';if(/fox\s*sports/.test(s))return'foxsports';if(/cbs\s*sports/.test(s))return'cbs';if(/nbc\s*sports/.test(s))return'nbcsports';if(/tnt\s*sports|\btnt\b/.test(s))return'tnt';if(/\btbs\b/.test(s))return'tbs';if(/nba\s*tv/.test(s))return'nbatev';if(/mlb\s*network/.test(s))return'mlbnetwork';if(/nhl\s*network/.test(s))return'nhlnetwork';if(/ufc\s*fight\s*pass/.test(s))return'ufcpass';if(/paramount/.test(s))return'paramount';if(/peacock/.test(s))return'peacock';if(/dazn/.test(s))return'dazn';if(/red\s*bull/.test(s))return'redbull';if(/monster\s*jam/.test(s))return'monsterjam';if(/rugby\s*pass/.test(s))return'rugbypass';if(/stadium/.test(s))return'stadium';if(/fanduel/.test(s))return'fanduel';if(/the\s*cw|\bcw\b/.test(s))return'thecw';return'network'}
function artworkSvg(id){const [name,a,sub]=THEMES[id]||THEMES.other;return logoSvg(THEMES,id)}
function eventArtworkSvg(league,away,home,state='pre',start='',awayLogo='',homeLogo='',awayShort='',homeShort='',eventName='',eventLogo=''){
 const [lname,a]=THEMES[league]||THEMES.other;const live=state==='in',post=state==='post';const when=live?'LIVE':post?'FINAL':start?new Date(start).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'UPCOMING';
 const escImg=v=>v?String(v).replace(/&/g,'&amp;').replace(/"/g,'%22'):'';const initials=s=>String(s||'').split(/\s+/).filter(Boolean).slice(0,3).map(x=>x[0]).join('').toUpperCase();
 if(league==='ufc'||league==='boxing'){const title=trunc(eventName||away||lname,42);return `<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 562">${shellDefs(a)}<rect width="1000" height="562" rx="26" fill="url(#bg)"/>${brand(a)}<text x="500" y="82" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="18" font-weight="900" letter-spacing="7">${esc(lname)} • ${esc(when)}</text>${eventLogo?`<image href="${escImg(eventLogo)}" x="330" y="105" width="340" height="150" preserveAspectRatio="xMidYMid meet"/>`:''}<text x="500" y="300" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="42" font-weight="900">${esc(title)}</text><text x="500" y="380" text-anchor="middle" fill="#fff" opacity=".75" font-family="Arial,sans-serif" font-size="14" font-weight="900" letter-spacing="5">OFFICIAL EVENT • STREAMS READY</text></svg>`}
 const side=(x,name,short,logo,label)=>`<g><rect x="${x-190}" y="115" width="380" height="190" rx="24" fill="#07101d" stroke="${a}" stroke-opacity=".5" stroke-width="2"/>${logo?`<image href="${escImg(logo)}" x="${x-54}" y="122" width="108" height="108" preserveAspectRatio="xMidYMid meet"/>`:`<text x="${x}" y="190" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="34" font-weight="900">${esc(initials(name)||short)}</text>`}<text x="${x}" y="255" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="24" font-weight="900">${esc(name||short)}</text><text x="${x}" y="284" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="10" font-weight="900" letter-spacing="4">${label}</text></g>`;
 return `<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 562">${shellDefs(a)}<rect width="1000" height="562" rx="26" fill="url(#bg)"/>${brand(a)}<text x="500" y="65" text-anchor="middle" fill="${a}" font-family="Arial,sans-serif" font-size="12" font-weight="900" letter-spacing="4">${esc(lname)} • ${esc(when)}</text>${side(245,away,awayShort,awayLogo,'AWAY')}<circle cx="500" cy="210" r="52" fill="#03060b" stroke="${a}" stroke-width="4"/><text x="500" y="220" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="24" font-weight="900">VS</text>${side(755,home,homeShort,homeLogo,'HOME')}<rect x="285" y="365" width="430" height="44" rx="22" fill="${a}" opacity=".12" stroke="${a}"/><text x="500" y="393" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="11" font-weight="900" letter-spacing="3">${live?'● LIVE':post?'FINAL':'UPCOMING'} • STREAMS READY</text></svg>`;
}
module.exports={THEMES,NETWORKS,artworkSvg,eventArtworkSvg,networkArtworkSvg:id=>logoSvg(NETWORKS,id),networkKey};