import http from "node:http";
import { spawn } from "node:child_process";

const PORT=Number(process.env.PORT||7000);
const UPSTREAM_PORT=Number(process.env.XSPORTSX_GATEWAY_PORT||7002);
const BACKEND_PORT=Number(process.env.XSPORTSX_BACKEND_PORT||7001);
const BASE=process.env.BASE_URL||"https://xsportsx.onrender.com";
const VERSION="4.5.5";
const ADDON_ID="com.xsportsx.sports.epg.v455";
const PREFIX="/v455";

const child=spawn(process.execPath,["gateway.js"],{env:{...process.env,PORT:String(UPSTREAM_PORT),XSPORTSX_BACKEND_PORT:String(BACKEND_PORT)},stdio:"inherit"});
child.on("error",e=>console.error("XSportsX gateway failed:",e));
child.on("exit",c=>console.error(`XSportsX gateway exited: ${c}`));

const leagues=[["nfl","NFL","football","nfl"],["ncaaf","NCAA Football","football","college-football"],["nba","NBA","basketball","nba"],["nhl","NHL","hockey","nhl"],["mlb","MLB","baseball","mlb"],["soccer","Soccer","soccer","eng.1"]];
let sportCache={at:0,metas:[]};
const xtreamCache=new Map();

function json(res,body,status=200){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","x-xsportsx-version":VERSION,"x-xsportsx-addon-id":ADDON_ID});res.end(JSON.stringify(body));}
function text(m){return `${m.name||""} ${m.description||""} ${(m.genres||[]).join(" ")}`.toLowerCase();}
function normalize(m,league){const id=String(m.id||`sport:${league}-${Math.random().toString(36).slice(2)}`);return {...m,id:id.startsWith("sport:")?id:`sport:${id}`,type:"channel",genres:[...new Set([...(m.genres||[]),"Sports",league.toUpperCase()])],posterShape:"landscape",behaviorHints:{...(m.behaviorHints||{})}};}
async function getJson(url){const r=await fetch(url);if(!r.ok)throw new Error(String(r.status));return r.json();}
async function loadSports(){const now=Date.now();if(now-sportCache.at<30000&&sportCache.metas.length)return sportCache.metas;const out=[];for(const [id,name,sport,espn] of leagues){try{const d=await getJson(`http://127.0.0.1:${UPSTREAM_PORT}/catalog/sport/${id}.json`);if(Array.isArray(d?.metas)&&d.metas.length){out.push(...d.metas.map(x=>normalize(x,id)));continue;}}catch{}try{const d=await getJson(`https://site.api.espn.com/apis/site/v2/sports/${sport}/${espn}/scoreboard?limit=100`);for(const ev of d.events||[]){const c=ev.competitions?.[0],teams=c?.competitors||[],home=teams.find(x=>x.homeAway==="home")?.team||teams[0]?.team||{},away=teams.find(x=>x.homeAway==="away")?.team||teams[1]?.team||{},state=c?.status?.type?.state,detail=c?.status?.type?.shortDetail||c?.status?.type?.detail||"Scheduled",logo=home.logo||away.logo;out.push(normalize({id:`sport:espn-${id}-${ev.id}`,name:`${away.displayName||"TBD"} vs ${home.displayName||"TBD"}`,poster:logo,background:logo,description:`${name}\n${detail}\n${ev.date||""}`,releaseInfo:ev.date||"",genres:["Sports",name,state==="in"?"LIVE":"Scheduled"]},id));}}catch{}}sportCache={at:now,metas:[...new Map(out.map(x=>[x.id,x])).values()]};return sportCache.metas;}
function isLeague(m,mode){const t=text(m),g=(m.genres||[]).map(x=>String(x).toLowerCase()),has=(...xs)=>xs.some(x=>t.includes(x)||g.includes(x));return mode==="ncaaf"?has("ncaa football","college football","ncaaf","cfb")&&!has("nfl"):mode==="nba"?has("nba")&&!has("wnba"):mode==="nfl"?has("nfl"):mode==="nhl"?has("nhl"):mode==="mlb"?has("mlb"):mode==="soccer"?has("soccer","premier league","mls","la liga"):mode==="ufc"?has("ufc","mma"):false;}
function filterSports(ms,mode){if(mode==="all")return ms;if(["nfl","ncaaf","nba","nhl","mlb","soccer","ufc"].includes(mode))return ms.filter(x=>isLeague(x,mode));if(mode==="live-now")return ms.filter(x=>/(^|\W)live(\W|$)|🔴/.test(text(x)));if(mode==="starting-soon")return ms.filter(x=>/starting soon|⏰/.test(text(x)));if(mode==="featured")return ms.filter(x=>/(^|\W)live(\W|$)|🔴|starting soon|⏰|ranked|cfp|title|playoff|championship|rivalry|ufc/.test(text(x)));return ms;}

function b64url(value){return Buffer.from(JSON.stringify(value),"utf8").toString("base64url");}
function decodeConfig(token){if(!token)return null;try{const v=JSON.parse(Buffer.from(token,"base64url").toString("utf8"));return v?.server&&v?.username&&v?.password?{server:String(v.server).replace(/\/$/,""),username:String(v.username),password:String(v.password)}:null;}catch{return null;}}
function requestConfig(u){const parts=u.pathname.split("/").filter(Boolean);const pIndex=parts.indexOf(PREFIX.slice(1));const token=pIndex>=0?parts[pIndex+1]:null;return decodeConfig(token)||((u.searchParams.get("server")&&u.searchParams.get("username")&&u.searchParams.get("password"))?{server:u.searchParams.get("server").replace(/\/$/,""),username:u.searchParams.get("username"),password:u.searchParams.get("password")}:null);}
function routePath(u){const parts=u.pathname.split("/").filter(Boolean),p=parts.indexOf(PREFIX.slice(1));if(p<0)return u.pathname;return "/"+parts.slice(p+2).join("/");}
function configManifestUrl(c){return `${BASE}${PREFIX}/${b64url(c)}/manifest.json`;}

function xtreamApi(c,action=""){const u=new URL(`${c.server}/player_api.php`);u.searchParams.set("username",c.username);u.searchParams.set("password",c.password);if(action)u.searchParams.set("action",action);return u;}
async function xtreamFetch(c,action=""){const r=await fetch(xtreamApi(c,action),{headers:{"user-agent":`XSportsX/${VERSION}`}});if(!r.ok)throw new Error(`Xtream HTTP ${r.status}`);return r.json();}
async function loadXtream(c){if(!c)return{configured:false,metas:[],error:"Xtream credentials are not configured."};const key=`${c.server}|${c.username}|${c.password}`,hit=xtreamCache.get(key);if(hit&&Date.now()-hit.at<30000)return hit.value;const info=await xtreamFetch(c);if(info?.user_info?.auth!==1)throw new Error(`Xtream authentication failed: ${info?.user_info?.status||"invalid credentials"}`);const [cats,streams]=await Promise.all([xtreamFetch(c,"get_live_categories"),xtreamFetch(c,"get_live_streams")]);const cm=new Map((Array.isArray(cats)?cats:[]).map(x=>[String(x.category_id),x.category_name||"Live TV"]));const metas=(Array.isArray(streams)?streams:[]).map(s=>{const cat=cm.get(String(s.category_id))||"Live TV",ext=String(s.container_extension||"m3u8").replace(/[^a-z0-9]/gi,"")||"m3u8";return{id:`xtream:${s.stream_id}`,type:"channel",name:s.name||`Channel ${s.stream_id}`,poster:s.stream_icon||undefined,background:s.stream_icon||undefined,description:`📺 ${cat}${s.epg_channel_id?`\nEPG: ${s.epg_channel_id}`:""}`,genres:["IPTV","Live TV",cat],behaviorHints:{isLive:true},xtream:{streamUrl:`${c.server}/live/${encodeURIComponent(c.username)}/${encodeURIComponent(c.password)}/${encodeURIComponent(s.stream_id)}.${ext}`,category:cat}}});const value={configured:true,metas,user:{status:info.user_info.status,expires:info.user_info.exp_date||null,maxConnections:info.user_info.max_connections||null},categories:[...cm.values()]};xtreamCache.set(key,{at:Date.now(),value});return value;}

function manifest(){const catalogs=[["sports-command-center","🏆 XSPORTSX • SPORTS COMMAND CENTER"],["live-now","🔴 LIVE NOW"],["starting-soon","⏰ STARTING SOON"],["featured","⭐ FEATURED"],["sports-epg","📺 ALL SPORTS • EPG"],["nfl","🏈 NFL"],["ncaaf","🏈 NCAA FOOTBALL"],["nba","🏀 NBA"],["nhl","🏒 NHL"],["mlb","⚾ MLB"],["ufc","🥊 UFC COMMAND CENTER"],["soccer","⚽ SOCCER"],["iptv-live","📡 MY IPTV • LIVE TV"]];return{id:ADDON_ID,version:VERSION,name:"XSportsX Sports Command Center",description:"Sports command center plus Xtream IPTV Live TV.",config:[{key:"server",type:"text",title:"Xtream Server URL",required:false},{key:"username",type:"text",title:"Xtream Username",required:false},{key:"password",type:"password",title:"Xtream Password",required:false}],behaviorHints:{configurable:true,configurationRequired:false},resources:[{name:"catalog",types:["channel"]},{name:"meta",types:["channel"],idPrefixes:["sport:","xtream:"]},{name:"stream",types:["channel"],idPrefixes:["sport:","xtream:"]}],types:["channel"],idPrefixes:["sport:","xtream:"],catalogs:catalogs.map(([id,name])=>({type:"channel",id,name,showInHome:true}))};}
function esc(s){return String(s||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));}
function configurePage(u){const c=requestConfig(u);if(c){const manifestUrl=configManifestUrl(c);return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>XSportsX Ready</title><style>body{margin:0;background:#07090d;color:#fff;font:16px system-ui;display:grid;place-items:center;min-height:100vh}main{width:min(560px,92vw);background:#11151d;padding:28px;border:1px solid #293241;border-radius:18px}input{width:100%;box-sizing:border-box;padding:13px;margin:8px 0 14px;background:#090c12;color:#fff;border:1px solid #343d4d;border-radius:10px}a,button{display:block;width:100%;box-sizing:border-box;padding:14px;margin-top:12px;border:0;border-radius:10px;background:#e21d2d;color:#fff;text-align:center;text-decoration:none;font-weight:700}</style></head><body><main><h1>✅ XSportsX is configured</h1><p>Your Nuvio-ready manifest has been generated. Copy this URL into Nuvio → Addons → Add Addon.</p><input readonly value="${esc(manifestUrl)}"><a href="${esc(manifestUrl)}">OPEN MANIFEST</a></main></body></html>`;}return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>XSportsX IPTV Setup</title><style>body{margin:0;background:#07090d;color:#fff;font:16px system-ui;display:grid;place-items:center;min-height:100vh}main{width:min(520px,92vw);background:#11151d;padding:28px;border:1px solid #252c38;border-radius:18px}label{display:block;margin:16px 0 7px}input{width:100%;box-sizing:border-box;padding:13px;border-radius:10px;border:1px solid #343d4d;background:#090c12;color:#fff}button{width:100%;margin-top:22px;padding:14px;border:0;border-radius:10px;background:#e21d2d;color:#fff;font-weight:700;font-size:16px}</style></head><body><main><h1>📡 XSportsX IPTV</h1><p>Enter the Xtream details from your authorized provider.</p><form method="get"><label>Xtream Server URL</label><input name="server" required placeholder="https://provider.example:8080"><label>Username</label><input name="username" required><label>Password</label><input type="password" name="password" required><button type="submit">GENERATE NUVIO MANIFEST</button></form></main></body></html>`;}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||"/",`http://${req.headers.host}`),path=routePath(u),c=requestConfig(u);if(path==="/configure"){res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"});return res.end(configurePage(u));}if(path==="/manifest.json")return json(res,manifest());if(path==="/health")return json(res,{ok:true,version:VERSION,addonId:ADDON_ID,xtream:true,configurationEncoding:"base64url-path",nuvioCompatible:true});if(path==="/xtream/status.json"){try{const x=await loadXtream(c);return json(res,{configured:x.configured,user:x.user||null,categories:x.categories?.length||0,channels:x.metas?.length||0,error:x.error||null})}catch(e){return json(res,{configured:!!c,ok:false,error:String(e?.message||e)},401)}}if(path==="/catalog/channel/iptv-live.json"){try{const x=await loadXtream(c);return json(res,{metas:x.metas||[],error:x.error||null})}catch(e){return json(res,{metas:[],error:String(e?.message||e)},401)}}if(path.startsWith("/meta/channel/xtream:")){try{const x=await loadXtream(c),id=decodeURIComponent(path.slice(13).replace(/\.json$/,"")),meta=x.metas.find(m=>m.id===id)||null;return json(res,{meta},meta?200:404)}catch(e){return json(res,{meta:null,error:String(e?.message||e)},401)}}if(path.startsWith("/stream/channel/xtream:")){try{const x=await loadXtream(c),id=decodeURIComponent(path.slice(15).replace(/\.json$/,"")),meta=x.metas.find(m=>m.id===id);return json(res,{streams:meta?.xtream?.streamUrl?[{name:`▶ ${meta.name}`,url:meta.xtream.streamUrl,title:meta.name}]:[]})}catch(e){return json(res,{streams:[],error:String(e?.message||e)},401)}}if(path.startsWith("/catalog/channel/")){const id=path.slice(17).replace(/\.json$/,""),ms=await loadSports();return json(res,{metas:filterSports(ms,id==="sports-command-center"?"featured":id==="sports-epg"?"all":id)})}if(path.startsWith("/meta/channel/")){const id=decodeURIComponent(path.slice(14).replace(/\.json$/,"")),ms=await loadSports(),meta=ms.find(m=>m.id===id)||null;return json(res,{meta},meta?200:404);}return json(res,{error:"Not found"},404);}catch(e){console.error("XSportsX request error",e);return json(res,{error:String(e?.message||e)},502);}});
server.keepAliveTimeout=120000;server.headersTimeout=125000;server.requestTimeout=120000;server.listen(PORT,"0.0.0.0",()=>console.log(`XSportsX ${VERSION} listening on ${PORT}`));