const http=require('http');
const crypto=require('crypto');
const axios=require('axios');

const PUBLIC_PORT=Number(process.env.PORT||10000);
const BACKEND_PORT=PUBLIC_PORT+1;
const SECRET=process.env.XSPORTSX_CONFIG_SECRET||'change-this-xsportsx-secret-in-render';
const KEY=crypto.createHash('sha256').update(SECRET).digest();
const VERSION='10.0.0';
const cache=new Map();
const inflight=new Map();
const LEAGUES={
 nfl:['NFL','football','nfl','🏈'],ncaaf:['NCAA Football','football','college-football','🏈'],
 nba:['NBA','basketball','nba','🏀'],wnba:['WNBA','basketball','wnba','🏀'],ncaab:['NCAA Basketball','basketball','mens-college-basketball','🏀'],
 mlb:['MLB','baseball','mlb','⚾'],nhl:['NHL','hockey','nhl','🏒'],
 mls:['MLS','soccer','usa.1','⚽'],epl:['Premier League','soccer','eng.1','⚽'],ucl:['UEFA Champions League','soccer','uefa.champions','⚽'],
 laliga:['LaLiga','soccer','esp.1','⚽'],seriea:['Serie A','soccer','ita.1','⚽'],bundesliga:['Bundesliga','soccer','ger.1','⚽'],ligue1:['Ligue 1','soccer','fra.1','⚽'],
 ufc:['UFC','mma','ufc','🥊'],boxing:['Boxing','boxing','boxing','🥊']
};
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/\+/g,' plus ').replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(Boolean).join(' ');
const cacheGet=(k,ttl,loader)=>{const h=cache.get(k);if(h&&h.exp>Date.now())return Promise.resolve(h.v);if(inflight.has(k))return inflight.get(k);const p=Promise.resolve().then(loader).then(v=>{cache.set(k,{v,exp:Date.now()+ttl});return v}).finally(()=>inflight.delete(k));inflight.set(k,p);return p};
function decrypt(t){try{const[a,b,c]=String(t||'').split('.');if(!a||!b||!c)return null;const d=crypto.createDecipheriv('aes-256-gcm',KEY,Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString())}catch{return null}}
function tokenFrom(req){const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(u.searchParams.get('config'))return u.searchParams.get('config');const p=u.pathname.split('/').filter(Boolean);const resources=new Set(['manifest.json','catalog','meta','stream']);const i=p.findIndex(x=>resources.has(x)||x.startsWith('catalog')||x.startsWith('meta')||x.startsWith('stream'));if(i>0)return p[i-1];if(p.length===1&&!['configure','health','xtream-health','artwork','qr'].includes(p[0])&&!p[0].endsWith('.json'))return p[0];return'';}
function config(req){return decrypt(tokenFrom(req));}
function base(req){return `${String(req.headers['x-forwarded-proto']||'https').split(',')[0]}://${req.headers.host||'localhost'}`;}
function json(res,status,obj){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-xsportsx-build':VERSION});res.end(JSON.stringify(obj));}
async function getJson(url,timeout=6000){return(await axios.get(url,{timeout,headers:{'User-Agent':`XSportsX/${VERSION}`,'Accept':'application/json'},maxContentLength:30000000})).data;}
function dateRange(){const n=new Date(),from=new Date(n),to=new Date(n);from.setUTCDate(from.getUTCDate()-2);to.setUTCDate(to.getUTCDate()+21);return`${from.toISOString().slice(0,10).replace(/-/g,'')}-${to.toISOString().slice(0,10).replace(/-/g,'')}`;}
function scoreboardUrl(id){const l=LEAGUES[id];return`https://site.api.espn.com/apis/site/v2/sports/${l[1]}/${l[2]}/scoreboard?dates=${dateRange()}&limit=100`;}
function normalizeEvent(league,e){const c=e.competitions?.[0],cs=c?.competitors||[],home=cs.find(x=>x.homeAway==='home')?.team||cs[0]?.team||{},away=cs.find(x=>x.homeAway==='away')?.team||cs[1]?.team||{},status=c?.status?.type||e.status?.type||{};return{id:String(e.id),league,leagueName:LEAGUES[league][0],start:e.date||'',state:status.state||'pre',home:{name:home.displayName||'TBD',short:home.abbreviation||'',logo:home.logo||''},away:{name:away.displayName||'TBD',short:away.abbreviation||'',logo:away.logo||''},detail:status.shortDetail||'Scheduled',broadcast:(c?.broadcasts||[]).flatMap(x=>x.names||[])};}
async function events(league){return cacheGet(`events:${league}:${dateRange()}`,20000,async()=>{try{const d=await getJson(scoreboardUrl(league),6000);return(Array.isArray(d?.events)?d.events:[]).map(e=>normalizeEvent(league,e)).filter(e=>e.home.name!=='TBD'||e.away.name!=='TBD');}catch(e){console.error(`[schedule:${league}]`,e.message);return[];}});}
async function allEvents(c){const ids=Array.isArray(c?.sports)?c.sports.filter(x=>LEAGUES[x]):Object.keys(LEAGUES);return(await Promise.all(ids.map(events))).flat().sort((a,b)=>new Date(a.start)-new Date(b.start));}
function parseM3U(text){const lines=String(text||'').split(/\r?\n/),out=[];for(let i=0;i<lines.length;i++){if(!/^#EXTINF/i.test(lines[i]))continue;const info=lines[i],url=lines[i+1]?.trim();if(!url||url.startsWith('#'))continue;out.push({name:clean((info.match(/,(.*)$/)||[])[1]||'Channel'),group:clean((info.match(/group-title=["']([^"']*)/i)||[])[1]||''),logo:(info.match(/tvg-logo=["']([^"']*)/i)||[])[1]||'',url,streamId:crypto.createHash('sha1').update(url).digest('hex').slice(0,14)});}return out;}
async function providerChannels(c){if(!c)return[];if(c.source==='m3u'){if(!c.m3uUrl)return[];return cacheGet(`m3u:${c.m3uUrl}`,30000,async()=>{const r=await axios.get(c.m3uUrl,{timeout:10000,responseType:'text',maxContentLength:50000000});return parseM3U(r.data);});}const x=c.xtream||{};if(!x.baseUrl||!x.username||!x.password)return[];return cacheGet(`xt:${x.baseUrl}:${x.username}`,30000,async()=>{const u=new URL(`${x.baseUrl.replace(/\/$/,'')}/player_api.php`);u.searchParams.set('username',x.username);u.searchParams.set('password',x.password);u.searchParams.set('action','get_live_streams');const d=await getJson(u.toString(),7000);return(Array.isArray(d)?d:[]).map(v=>({name:clean(v.name||v.stream_display_name||''),group:clean(v.category_name||''),logo:v.stream_icon||'',streamId:String(v.stream_id||v.id||''),streamType:v.stream_type||'live'})).filter(v=>v.name);});}
const SPORT_RE=/\b(sport|sports|espn|espn plus|fox sports|fs1|fs2|tnt|tbs|nba|mlb|nhl|nfl|ncaaf|ncaab|wnba|sec network|acc network|big ten|baseball|basketball|football|hockey|ufc|mma|boxing|fight|dazn|prime video|paramount|peacock|sportsnet|tsn|fight pass|youtube)\b/i;
function score(event,ch){const text=norm(`${ch.name} ${ch.group}`),teams=[event.away.name,event.home.name].filter(x=>x&&x!=='TBD');let s=SPORT_RE.test(text)?8:0;for(const t of teams){const n=norm(t);if(n&&text.includes(n))s+=48;const words=n.split(' ').filter(w=>w.length>=4);for(const w of words)if(text.includes(w))s+=8;}for(const b of event.broadcast||[])if(text.includes(norm(b)))s+=35;const nets={nfl:['nfl network','espn','espn plus','fox','fs1','cbs','nbc','amazon prime'],ncaaf:['espn','espn plus','sec network','acc network','big ten','fox','fs1','cbs','peacock'],nba:['espn','espn plus','tnt','tbs','abc','nba tv'],wnba:['espn','espn plus','nba tv'],ncaab:['espn','espn plus','tnt','cbs','fox','fs1','big ten','sec network','acc network'],mlb:['espn','espn plus','fox','fs1','tbs','mlb network'],nhl:['espn','espn plus','tnt','tbs','nhl network','sportsnet','tsn'],mls:['apple tv','fox','fs1','espn'],epl:['nbc','peacock','usa network'],ufc:['espn plus','espn','ufc','ufc fight pass','tnt sports','youtube'],boxing:['dazn','espn plus','espn','prime video','fox sports','fs1','tnt sports','youtube','paramount']};
for(const n of (nets[event.league]||[]))if(text.includes(norm(n)))s+=10;
if((event.league==='ufc'||event.league==='boxing')&&(/\b(tbd|contender|road to ufc|fight night|ufc|boxing|fight)\b/i.test(event.home.name+' '+event.away.name+' '+event.detail)))s+=20;
return Math.min(100,s);}
function streamUrl(c,ch){if(c.source==='m3u')return ch.url;const x=c.xtream;return`${x.baseUrl.replace(/\/$/,'')}/live/${encodeURIComponent(x.username)}/${encodeURIComponent(x.password)}/${encodeURIComponent(ch.streamId)}.ts`;}
function meta(req,e){return{id:`sport:${e.league}:${e.id}`,type:'tv',name:`${e.away.short||e.away.name} vs ${e.home.short||e.home.name}`,poster:`${base(req)}/artwork/${e.league}.svg`,background:`${base(req)}/artwork/${e.league}.svg`,posterShape:'landscape',description:`${e.leagueName} • ${e.detail}\n${e.start}`,releaseInfo:e.start,genres:['Sports',e.leagueName],behaviorHints:{isPlayable:true}};}
function manifest(req,c){const sports=Array.isArray(c?.sports)?c.sports.filter(x=>LEAGUES[x]):[];const cats=[{type:'tv',id:'live-now',name:'🔴 LIVE NOW',extra:[],showInHome:true},{type:'tv',id:'starting-soon',name:'⏰ STARTING SOON',extra:[],showInHome:true},...sports.map(id=>({type:'tv',id,name:`${LEAGUES[id][3]} ${LEAGUES[id][0]}`,extra:[],showInHome:true}))];return{id:`community.xsportsx.10.${crypto.createHash('sha256').update(JSON.stringify(sports)).digest('hex').slice(0,12)}`,version:VERSION,name:'XSportsX',description:'Live sports schedule + authorized Xtream/M3U stream matching.',resources:[{name:'catalog',types:['tv']},{name:'meta',types:['tv']},{name:'stream',types:['tv']}],types:['tv'],idPrefixes:['sport:','xtream:'],catalogs:cats,behaviorHints:{configurable:false,configurationRequired:false},logo:`${base(req)}/artwork/other.svg`};}
async function intercept(req,res){const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`),p=u.pathname,c=config(req);
if(p==='/health')return json(res,200,{ok:true,name:'XSportsX',version:VERSION});
if(p==='/manifest.json'&&c)return json(res,200,manifest(req,c));
const cm=p.match(/^\/catalog\/tv\/([^/]+)\.json$/);if(cm&&c){const id=cm[1],allowed=new Set(Array.isArray(c.sports)?c.sports:[]);let ev=[];if(id==='live-now'||id==='starting-soon'){ev=await allEvents(c);ev=id==='live-now'?ev.filter(e=>e.state==='in'):ev.filter(e=>e.state==='pre').slice(0,100);}else if(allowed.has(id)){ev=await events(id);}else return json(res,200,{metas:[]});return json(res,200,{metas:ev.map(e=>meta(req,e))});}
const mm=p.match(/^\/meta\/tv\/sport:([^:]+):([^/]+)\.json$/);if(mm&&c){const e=(await events(mm[1])).find(x=>x.id===mm[2]);return e?json(res,200,{meta:meta(req,e)}):json(res,404,{error:'Event not found'});}
const sm=p.match(/^\/stream\/tv\/sport:([^:]+):([^/]+)\.json$/);if(sm&&c){const league=sm[1],id=sm[2];if(!(Array.isArray(c.sports)?c.sports:[]).includes(league))return json(res,200,{streams:[]});const e=(await events(league)).find(x=>x.id===id);if(!e)return json(res,200,{streams:[]});const channels=await providerChannels(c);let ranked=channels.map(ch=>({...ch,score:score(e,ch)})).filter(ch=>ch.score>=18).sort((a,b)=>b.score-a.score);if(!ranked.length&&channels.length){ranked=channels.filter(ch=>SPORT_RE.test(`${ch.name} ${ch.group}`)).map(ch=>({...ch,score:10})).slice(0,6);}ranked=ranked.slice(0,10);return json(res,200,{streams:ranked.map(ch=>({title:`${ch.name} • ${ch.score}% match`,url:streamUrl(c,ch),behaviorHints:{notWebReady:true}}))});}
return false;}

process.env.PORT=String(BACKEND_PORT);
require('./server.js');
const proxy=http.createServer(async(req,res)=>{try{if(await intercept(req,res)!==false)return;const u=new URL(req.url||'/','http://local');const upstream=http.request({hostname:'127.0.0.1',port:BACKEND_PORT,path:u.pathname+(u.search||''),method:req.method,headers:{...req.headers,host:`127.0.0.1:${BACKEND_PORT}`}},r=>{res.writeHead(r.statusCode||502,{...r.headers,'x-xsportsx-build':VERSION});r.pipe(res)});upstream.on('error',e=>json(res,502,{error:e.message}));req.pipe(upstream);}catch(e){json(res,500,{error:e.message});}});
proxy.listen(PUBLIC_PORT,'0.0.0.0',()=>console.log(`XSportsX ${VERSION} public ${PUBLIC_PORT}; backend ${BACKEND_PORT}`));
