const http=require('http');
const crypto=require('crypto');
const axios=require('axios');

const PUBLIC_PORT=Number(process.env.PORT||10000);
const BACKEND_PORT=PUBLIC_PORT+1;
const SECRET=process.env.XSPORTSX_CONFIG_SECRET||'change-this-xsportsx-secret-in-render';
const KEY=crypto.createHash('sha256').update(SECRET).digest();
const VERSION='9.9.0';
const cache=new Map();
const inflight=new Map();
const LEAGUES={
  nfl:['NFL','football','nfl','🏈'],ncaaf:['NCAA Football','football','college-football','🏈'],nba:['NBA','basketball','nba','🏀'],wnba:['WNBA','basketball','wnba','🏀'],ncaab:['NCAA Basketball','basketball','mens-college-basketball','🏀'],mlb:['MLB','baseball','mlb','⚾'],nhl:['NHL','hockey','nhl','🏒'],mls:['MLS','soccer','usa.1','⚽'],epl:['Premier League','soccer','eng.1','⚽'],ucl:['UEFA Champions League','soccer','uefa.champions','⚽'],laliga:['LaLiga','soccer','esp.1','⚽'],seriea:['Serie A','soccer','ita.1','⚽'],bundesliga:['Bundesliga','soccer','ger.1','⚽'],ligue1:['Ligue 1','soccer','fra.1','⚽'],ufc:['UFC','mma','ufc','🥊'],boxing:['Boxing','boxing','boxing','🥊']
};
const SPORT=Object.keys(LEAGUES);
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const norm=v=>clean(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/\+/g,' plus ').replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(Boolean).join(' ');
function decrypt(t){try{const[a,b,c]=String(t||'').split('.');if(!a||!b||!c)return null;const d=crypto.createDecipheriv('aes-256-gcm',KEY,Buffer.from(a,'base64url'));d.setAuthTag(Buffer.from(b,'base64url'));return JSON.parse(Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString())}catch{return null}}
function tokenFrom(req){const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const q=u.searchParams.get('config');if(q)return q;const p=u.pathname.split('/').filter(Boolean);const resources=new Set(['manifest.json','catalog','meta','stream']);const i=p.findIndex(x=>resources.has(x)||x.startsWith('catalog')||x.startsWith('meta')||x.startsWith('stream'));if(i>0)return p[i-1];if(p.length===1&&!['configure','health','xtream-health','artwork','qr'].includes(p[0])&&!p[0].endsWith('.json'))return p[0];return'';}
function config(req){return decrypt(tokenFrom(req));}
function base(req){return `${String(req.headers['x-forwarded-proto']||'https').split(',')[0]}://${req.headers.host||'localhost'}`;}
function cached(k,ttl,loader){const h=cache.get(k);if(h&&h.exp>Date.now())return Promise.resolve(h.v);if(inflight.has(k))return inflight.get(k);const p=Promise.resolve().then(loader).then(v=>{cache.set(k,{v,exp:Date.now()+ttl});return v}).finally(()=>inflight.delete(k));inflight.set(k,p);return p;}
async function getJson(url,timeout=5000){return (await axios.get(url,{timeout,headers:{'User-Agent':`XSportsX/${VERSION}`,'Accept':'application/json'},maxContentLength:20000000})).data;}
function dateRange(){const n=new Date(),from=new Date(n),to=new Date(n);from.setUTCDate(from.getUTCDate()-1);to.setUTCDate(to.getUTCDate()+14);return `${from.toISOString().slice(0,10).replace(/-/g,'')}-${to.toISOString().slice(0,10).replace(/-/g,'')}`;}
function scoreboardUrl(league){const l=LEAGUES[league];return `https://site.api.espn.com/apis/site/v2/sports/${l[1]}/${l[2]}/scoreboard?dates=${dateRange()}&limit=100`;}
function normalizeEvent(league,e){const c=e.competitions?.[0],cs=c?.competitors||[],home=cs.find(x=>x.homeAway==='home')?.team||cs[0]?.team||{},away=cs.find(x=>x.homeAway==='away')?.team||cs[1]?.team||{},state=c?.status?.type?.state||e.status?.type?.state||'pre';return{id:String(e.id),league,leagueName:LEAGUES[league][0],start:e.date||'',state,home:{name:home.displayName||'TBD',short:home.abbreviation||'',logo:home.logo||''},away:{name:away.displayName||'TBD',short:away.abbreviation||'',logo:away.logo||''},detail:c?.status?.type?.shortDetail||e.status?.type?.shortDetail||'Scheduled',broadcast:(c?.broadcasts||[]).flatMap(x=>x.names||[])};}
async function events(league){return cached(`events:${league}:${dateRange()}`,20000,async()=>{try{const d=await getJson(scoreboardUrl(league),5000);return(Array.isArray(d?.events)?d.events:[]).map(e=>normalizeEvent(league,e)).filter(e=>e.home.name!=='TBD'||e.away.name!=='TBD');}catch{return[];}});}
async function providerChannels(c){if(!c)return[];if(c.source==='m3u'){return cached(`m3u:${c.m3uUrl}`,30000,async()=>{const r=await axios.get(c.m3uUrl,{timeout:8000,responseType:'text',maxContentLength:30000000});const lines=String(r.data||'').split(/\r?\n/),out=[];for(let i=0;i<lines.length;i++){if(!/^#EXTINF/i.test(lines[i]))continue;const url=lines[i+1]?.trim();if(!url||url.startsWith('#'))continue;const name=clean((lines[i].match(/,(.*)$/)||[])[1]||'Channel');const group=(lines[i].match(/group-title=[\"']([^\"']*)/i)||[])[1]||'';out.push({name,group,url});}return out;});}
return cached(`xt:${c.xtream?.baseUrl}:${c.xtream?.username}`,30000,async()=>{const x=c.xtream||{};if(!x.baseUrl||!x.username||!x.password)return[];const u=new URL(`${x.baseUrl.replace(/\/$/,'')}/player_api.php`);u.searchParams.set('username',x.username);u.searchParams.set('password',x.password);u.searchParams.set('action','get_live_streams');const d=await getJson(u.toString(),5000);return(Array.isArray(d)?d:[]).map(x=>({name:clean(x.name||x.stream_display_name||''),group:clean(x.category_name||''),streamId:String(x.stream_id||x.id||''),logo:x.stream_icon||''})).filter(x=>x.name);});}
function score(event,ch){const text=norm(`${ch.name} ${ch.group}`),teams=[event.away.name,event.home.name];let s=0;for(const t of teams){const n=norm(t);if(n&&text.includes(n))s+=40;for(const w of n.split(' ').filter(x=>x.length>3))if(text.includes(w))s+=10;}const nets=['espn','espn plus','fox','fs1','fs2','cbs','nbc','abc','tnt','tbs','paramount','peacock','sportsnet','tsn','mlb network','nba tv','nfl network','nhl network','ufc fight pass'];for(const n of nets)if(text.includes(norm(n)))s+=5;if(text.includes(norm(event.leagueName)))s+=10;return Math.min(100,s);}
function streamUrl(c,ch){if(c.source==='m3u')return ch.url;const x=c.xtream;return `${x.baseUrl.replace(/\/$/,'')}/live/${encodeURIComponent(x.username)}/${encodeURIComponent(x.password)}/${encodeURIComponent(ch.streamId)}.ts`;}
function json(res,status,obj){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-xsportsx-build':VERSION});res.end(JSON.stringify(obj));}
function manifest(req,c){const sports=Array.isArray(c?.sports)?c.sports.filter(x=>LEAGUES[x]):[];return{id:`community.xsportsx.9.9.${crypto.createHash('sha256').update(JSON.stringify(sports)).digest('hex').slice(0,12)}`,version:VERSION,name:'XSportsX',description:'Premium live sports for Nuvio using your selected leagues and authorized Xtream/M3U source.',resources:[{name:'catalog',types:['tv']},{name:'meta',types:['tv']},{name:'stream',types:['tv']}],types:['tv'],idPrefixes:['sport:','xtream:'],catalogs:sports.map(id=>({type:'tv',id,name:`${LEAGUES[id][3]} ${LEAGUES[id][0]}`,extra:[],showInHome:true})),behaviorHints:{configurable:false,configurationRequired:false},logo:`${base(req)}/artwork/other.svg`};}
async function intercept(req,res){const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);const p=u.pathname;const c=config(req);
if(p==='/health'){return json(res,200,{ok:true,name:'XSportsX',version:VERSION,hotfix:true});}
if(p==='/manifest.json'&&c){return json(res,200,manifest(req,c));}
const cm=p.match(/^\/catalog\/tv\/([^/]+)\.json$/);if(cm&&c){const id=cm[1],allowed=new Set(Array.isArray(c.sports)?c.sports:[]);if(!allowed.has(id))return json(res,200,{metas:[]});const ev=await events(id);return json(res,200,{metas:ev.map(e=>({id:`sport:${e.league}:${e.id}`,type:'tv',name:`${e.away.short||e.away.name} vs ${e.home.short||e.home.name}`,poster:`${base(req)}/artwork/${e.league}.svg`,background:`${base(req)}/artwork/${e.league}.svg`,posterShape:'landscape',description:`${e.leagueName} • ${e.detail}\n${e.start}`,releaseInfo:e.start,genres:['Sports',e.leagueName],behaviorHints:{isPlayable:true}}))});}
const sm=p.match(/^\/stream\/tv\/sport:([^:]+):([^/]+)\.json$/);if(sm&&c){const league=sm[1],eventId=sm[2];if(!(Array.isArray(c.sports)?c.sports:[]).includes(league))return json(res,200,{streams:[]});const list=await events(league);const e=list.find(x=>x.id===eventId);if(!e)return json(res,200,{streams:[]});const channels=await providerChannels(c);const ranked=channels.map(ch=>({...ch,score:score(e,ch)})).filter(x=>x.score>=20).sort((a,b)=>b.score-a.score).slice(0,8);return json(res,200,{streams:ranked.map(ch=>({title:`${ch.name} • ${ch.score}% match`,url:streamUrl(c,ch),behaviorHints:{notWebReady:true}}))});}
return false;}

process.env.PORT=String(BACKEND_PORT);
require('./server.js');
const proxy=http.createServer(async(req,res)=>{try{const handled=await intercept(req,res);if(handled!==false)return;const u=new URL(req.url||'/','http://local');const upstream=http.request({hostname:'127.0.0.1',port:BACKEND_PORT,path:u.pathname+(u.search||''),method:req.method,headers:{...req.headers,host:`127.0.0.1:${BACKEND_PORT}`}},r=>{res.writeHead(r.statusCode||502,{...r.headers,'x-xsportsx-build':VERSION});r.pipe(res)});upstream.on('error',e=>json(res,502,{error:e.message}));req.pipe(upstream);}catch(e){json(res,500,{error:e.message});}});
proxy.listen(PUBLIC_PORT,'0.0.0.0',()=>console.log(`XSportsX ${VERSION} hotfix public ${PUBLIC_PORT}; backend ${BACKEND_PORT}`));
