import http from "node:http";
import crypto from "node:crypto";

const PORT=Number(process.env.XSPORTSX_NEWS_PORT||7098);
const BASE=process.env.BASE_URL||"https://xsportsx.onrender.com";
const PREFIX="/v516";
const SECRET=process.env.XSPORTSX_CONFIG_SECRET||crypto.randomBytes(32).toString("hex");
const KEY=crypto.createHash("sha256").update(SECRET).digest();
const GROUPS={"ESPN":["espn","espn2","espnu","espn news","espnews","espn deportes","espn+","espn plus"],"ACC Network":["acc network","accn"],"SEC Network":["sec network","secn"],"Big Ten Network":["big ten network","btn"],"NFL Network":["nfl network","nfln"],"MLB Network":["mlb network","mlbn"],"NBA TV":["nba tv","nbatv"],"NHL Network":["nhl network","nhln"],"CBS Sports":["cbs sports network","cbs sports","cbssn"],"Fox Sports":["fox sports","fox sports 1","fox sports 2","fs1","fs2"],"Golf Channel":["golf channel"],"TNT Sports":["tnt sports","tnt"],"NBC Sports":["nbc sports"],"beIN Sports":["bein sports","beinsports"],"Sportsnet":["sportsnet"],"Tennis Channel":["tennis channel"]};
const cache=new Map();
const norm=v=>String(v||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const slug=v=>norm(v).replace(/\s+/g,"-");
function json(res,b,status=200,age=15){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":`public,max-age=${age},stale-while-revalidate=60`,"access-control-allow-origin":"*","x-xsportsx-version":"5.0.18"});res.end(JSON.stringify(b));}
function cfgFrom(req){try{const u=new URL(req.url,"http://localhost"),t=u.searchParams.get("config");if(!t)return null;const raw=Buffer.from(decodeURIComponent(t),"base64url");const d=crypto.createDecipheriv("aes-256-gcm",KEY,raw.subarray(0,12));d.setAuthTag(raw.subarray(12,28));const v=JSON.parse(Buffer.concat([d.update(raw.subarray(28)),d.final()]).toString());return v?.server&&v?.username&&v?.password?{server:String(v.server).replace(/\/+$/,""),username:String(v.username),password:String(v.password)}:null}catch{return null}}
async function api(c,action){const u=new URL(`${c.server}/player_api.php`);u.searchParams.set("username",c.username);u.searchParams.set("password",c.password);u.searchParams.set("action",action);const r=await fetch(u,{headers:{accept:"application/json"},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`Xtream HTTP ${r.status}`);return r.json()}
function groupFor(name,cat){const v=norm(`${name} ${cat}`);for(const [g,a] of Object.entries(GROUPS))if(a.some(x=>v.includes(norm(x))))return g;return null}
async function data(c){const k=`${c.server}|${c.username}`;const h=cache.get(k);if(h&&Date.now()-h.at<300000)return h.v;try{const [cats,streams]=await Promise.all([api(c,"get_live_categories"),api(c,"get_live_streams")]);const cm=new Map((Array.isArray(cats)?cats:[]).map(x=>[String(x.category_id),x.category_name||"Live TV"]));const metas=(Array.isArray(streams)?streams:[]).map(s=>{const cat=cm.get(String(s.category_id))||s.category_name||s.category||"Live TV";const ext=String(s.container_extension||"ts").replace(/[^a-z0-9]/gi,"")||"ts";return{id:`xtream:${s.stream_id}`,name:s.name||`Channel ${s.stream_id}`,poster:s.stream_icon||undefined,icon:s.stream_icon||undefined,category:cat,url:`${c.server}/live/${encodeURIComponent(c.username)}/${encodeURIComponent(c.password)}/${encodeURIComponent(s.stream_id)}.${ext}`}});const value={metas};cache.set(k,{at:Date.now(),v:value});return value}catch(e){return h?.v||{metas:[]}}}
function card(group,channels){const icon=channels.find(x=>x.poster)?.poster||`${BASE}${PREFIX}/assets/news/${slug(group)}.svg`;return{id:`news:${slug(group)}`,type:"channel",name:group,poster:icon,background:icon,logo:icon,description:`${channels.length} live ${group} channel${channels.length===1?"":"s"} from your Xtream provider`,genres:["Sports News",group],behaviorHints:{isLive:true},newsGroup:group}};
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://localhost"),m=u.pathname.match(/\/(catalog|meta|stream)\/channel\/([^/]+?)(?:\.json)?$/i);if(!m)return json(res,{error:"not found"},404,0);const cfg=cfgFrom(req);if(!cfg)return json(res,{error:"missing configuration"},400,0);const d=await data(cfg),kind=m[1],raw=decodeURIComponent(m[2]);if(kind==="catalog"){if(raw.toLowerCase()==="sports-news"){const cards=Object.entries(GROUPS).map(([g])=>{const ch=d.metas.filter(x=>groupFor(x.name,x.category)===g);return ch.length?card(g,ch):null}).filter(Boolean);return json(res,{metas:cards});}if(raw.toLowerCase().startsWith("news:")){const g=Object.keys(GROUPS).find(x=>slug(x)===raw.slice(5))||raw.slice(5).replace(/-/g," ");const ch=d.metas.filter(x=>groupFor(x.name,x.category)===g);return json(res,{metas:[card(g,ch)]});}return json(res,{metas:[]});}if(kind==="meta"){const g=raw.toLowerCase().startsWith("news:")?(Object.keys(GROUPS).find(x=>slug(x)===raw.slice(5))||raw.slice(5).replace(/-/g," ")):null;if(g){const ch=d.metas.filter(x=>groupFor(x.name,x.category)===g);return json(res,{meta:card(g,ch)},200,30)}const x=d.metas.find(x=>x.id===raw);return json(res,{meta:x?{id:x.id,type:"channel",name:x.name,poster:x.poster,background:x.poster,logo:x.poster,description:x.category,genres:["Sports News",x.category],behaviorHints:{isLive:true}}:null},200,30)}if(kind==="stream"){let ch=[];if(raw.toLowerCase().startsWith("news:")){const g=Object.keys(GROUPS).find(x=>slug(x)===raw.slice(5))||raw.slice(5).replace(/-/g," ");ch=d.metas.filter(x=>groupFor(x.name,x.category)===g)}else{const x=d.metas.find(x=>x.id===raw);if(x)ch=[x]}return json(res,{streams:ch.map(x=>({name:`▶ ${x.name}`,title:x.name,url:x.url,description:x.category,behaviorHints:{isLive:true}}))},200,15)}}catch(e){return json(res,{error:"Xtream news route failed",detail:String(e.message||e)},502,0)}});
server.listen(PORT,"127.0.0.1",()=>console.log(`XSportsX news overlay on ${PORT}`));
