const crypto=require('crypto');

const SPORT_WORDS=/\b(sport|sports|espn|espn\+|fox sports|fs1|fs2|tnt|nba|mlb|nhl|nfl|ncaaf|ncaab|wnba|sec network|acc network|big ten|bally|msg|regional sports|baseball|basketball|football|hockey|soccer|tennis|golf|cbs sports|nbc sports|bein|sky sport|f1|formula|racing|ufc|boxing|fight|wrestling)\b/i;
const STOP=new Set(['the','and','at','vs','v','fc','cf','sc','club','team','live','tv','hd','fhd','uhd','4k','usa','us','network','sports','sport','channel','east','west','main','backup','feed','event']);
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function norm(v){return clean(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x&&!STOP.has(x)).join(' ')}
function similarity(a,b){const aa=new Set(norm(a).split(' ').filter(Boolean)),bb=new Set(norm(b).split(' ').filter(Boolean));if(!aa.size||!bb.size)return 0;let hits=0;for(const x of aa)if(bb.has(x))hits++;return Math.round((hits/Math.min(aa.size,bb.size)*70+hits/new Set([...aa,...bb]).size*30))}
function parseM3U(text){const lines=String(text||'').split(/\r?\n/),out=[];for(let i=0;i<lines.length;i++){if(!/^#EXTINF/i.test(lines[i]))continue;const info=lines[i],url=lines[i+1]?.trim();if(!url||url.startsWith('#'))continue;out.push({name:clean((info.match(/,(.*)$/)||[])[1]||'Channel'),logo:(info.match(/tvg-logo=["']([^"']*)/i)||[])[1]||'',category:(info.match(/group-title=["']([^"']*)/i)||[])[1]||'Live TV',url,streamId:crypto.createHash('sha1').update(url).digest('hex').slice(0,12)})}return out}
function epgTitle(x){return clean(x.title||x.name||x.programme||x.program_name||x.description||'')}
function epgItems(raw){const rows=Array.isArray(raw)?raw:(raw?.epg_listings||raw?.programmes||raw?.programs||[]);return rows.map(x=>({title:epgTitle(x),description:clean(x.description||x.desc||''),start:x.start||x.start_time||x.startTime||x.date||'',end:x.end||x.end_time||x.endTime||'',channelId:String(x.channel_id||x.channelId||x.stream_id||x.streamId||''),id:String(x.id||x.program_id||'')})).filter(x=>x.title)}
function isEventTitle(title){const t=clean(title);return SPORT_WORDS.test(t)&&!/^(commercial|paid program|sign off|sign-on|news|weather|music|movie|documentary|talk show|infomercial)\b/i.test(t)}
function groupEvents(items){const map=new Map();for(const x of items){if(!isEventTitle(x.title))continue;const key=`${norm(x.title)}|${String(x.start).slice(0,13)}`;const old=map.get(key);if(old){if(x.end&&!old.end)old.end=x.end;if(x.channelId&&!old.channelIds.includes(x.channelId))old.channelIds.push(x.channelId);continue}map.set(key,{...x,channelIds:x.channelId?[x.channelId]:[]})}return [...map.values()]}
function matchChannels(event,channels){const wanted=`${event.title} ${event.description}`;return channels.map(c=>{const score=Math.max(similarity(wanted,c.name),similarity(event.title,c.category));return{...c,score}}).filter(c=>c.score>=35).sort((a,b)=>b.score-a.score).slice(0,20)}
function buildProviderEvents(epg,channels,source='xtream'){return groupEvents(epgItems(epg)).map((e,i)=>({id:`provider:event:${crypto.createHash('sha1').update(`${source}|${e.title}|${e.start}`).digest('hex').slice(0,16)}`,name:e.title,description:e.description,releaseInfo:e.start,start:e.start,end:e.end,source,channels:matchChannels(e,channels),providerEvent:e}))}
module.exports={parseM3U,epgItems,groupEvents,matchChannels,buildProviderEvents,isEventTitle};