import { TTLCache, CircuitBreaker, fetchJson, fetchText, matchScore, rankStreams, eventKey, normalizeName } from "./core.js";

const cache = new TTLCache();
const breakers = new CircuitBreaker({ failureThreshold: 3, cooldownMs: 60000 });
const inFlight = new Map();

const SPORTS = {
  nfl:["football","nfl"], nhl:["hockey","nhl"], nba:["basketball","nba"], mlb:["baseball","mlb"], ncaaf:["football","college-football"], ncaab:["basketball","mens-college-basketball"], wnba:["basketball","wnba"], mls:["soccer","usa.1"], "premier-league":["soccer","eng.1"], "la-liga":["soccer","esp.1"], ufc:["mma","ufc"], f1:["racing","f1"], motogp:["racing","motogp"], boxing:["boxing","boxing"], atp:["tennis","atp"], wta:["tennis","wta"], pga:["golf","pga"], rugby:["rugby","rugby"], cricket:["cricket","cricket"], pdc:["darts","darts"], afl:["football","aus.1"]
};
const sports=(process.env.SPORTS||Object.keys(SPORTS).join(",")).split(",").map(x=>x.trim()).filter(Boolean);
const m3uSources=readJson("AUTHORIZED_M3U_SOURCES",[]), xtreamSources=readJson("AUTHORIZED_XTREAM_SOURCES",[]), directSources=readJson("AUTHORIZED_EVENT_STREAMS",[]), jsonFeeds=readJson("AUTHORIZED_JSON_EVENT_FEEDS",[]), officialLinks=readJson("OFFICIAL_WATCH_LINKS",{});
const timeout=Number(process.env.REQUEST_TIMEOUT_MS||9000);
function readJson(key,fallback){try{return JSON.parse(process.env[key]||JSON.stringify(fallback));}catch{return fallback;}}
function ttlForSport(sport){return ["nfl","nba","nhl","mlb","wnba","ncaaf","ncaab"].includes(sport)?30000:60000;}
function team(t={}){return{id:String(t.id||""),name:t.displayName||t.name||"",short:t.abbreviation||t.short||"",logo:t.logo||t.logos?.[0]?.href||""};}
function espnEvent(e,sport){const c=e?.competitions?.[0];if(!c)return null;const home=c.competitors?.find(x=>x.homeAway==="home")||c.competitors?.[1],away=c.competitors?.find(x=>x.homeAway==="away")||c.competitors?.[0];if(!home||!away)return null;const status=c.status?.type||{};return{id:`sport:${e.id}`,eventId:String(e.id),canonicalId:eventKey({league:e?.league?.abbreviation||sport,home:team(home.team),away:team(away.team),start:e.date||c.date}),sport,league:e?.league?.abbreviation||sport.toUpperCase(),title:`${away.team?.displayName||"Away"} vs ${home.team?.displayName||"Home"}`,state:status.state||"pre",detail:status.shortDetail||status.detail||"",statusName:status.name||"",start:e.date||c.date,venue:c.venue?.fullName||"",broadcast:(c.broadcasts||[]).flatMap(x=>x.names||[]),home:{...team(home.team),score:home.score??null},away:{...team(away.team),score:away.score??null},links:e.links||[]};}
async function espnScoreboard(sport,date){const pair=SPORTS[sport];if(!pair)return[];const key=`espn:${sport}:${date}`,cached=cache.get(key);if(cached)return cached;if(breakers.isOpen(`espn:${sport}`))return cache.getStale(key)||[];if(inFlight.has(key))return inFlight.get(key);const task=(async()=>{try{const[group,league]=pair,url=`https://site.api.espn.com/apis/site/v2/sports/${group}/${league}/scoreboard?dates=${date.replaceAll("-","")}`,data=await fetchJson(url,{},timeout);breakers.success(`espn:${sport}`);return cache.set(key,(data.events||[]).map(e=>espnEvent(e,sport)).filter(Boolean),ttlForSport(sport));}catch(e){breakers.failure(`espn:${sport}`);return cache.getStale(key)||[];}finally{inFlight.delete(key);}})();inFlight.set(key,task);return task;}
async function jsonEventFeeds(){const out=[];for(const src of jsonFeeds){if(!src?.url||breakers.isOpen(`json:${src.name||src.url}`))continue;try{const data=await fetchJson(src.url,{headers:src.headers||{}},timeout),items=Array.isArray(data)?data:(data.events||data.items||[]);for(const x of items){if(!x?.id||!x.home||!x.away)continue;const home=team(x.home),away=team(x.away);out.push({id:`sport:${x.id}`,eventId:String(x.id),canonicalId:eventKey({league:x.league||src.name||"SPORTS",home,away,start:x.start}),sport:x.sport||"other",league:x.league||src.name||"SPORTS",title:x.title||`${away.name} vs ${home.name}`,state:x.state||"pre",detail:x.detail||"",statusName:x.statusName||"",start:x.start,venue:x.venue||"",broadcast:x.broadcast||[],home:{...home,score:x.home.score??null},away:{...away,score:x.away.score??null},links:x.links||[]});}breakers.success(`json:${src.name||src.url}`);}catch{breakers.failure(`json:${src.name||src.url}`);}}return out;}
export async function getEvents({days=1,date=new Date()}={}){const dates=[],base=new Date(date);for(let i=0;i<Math.max(1,Math.min(Number(days)||1,7));i++){const d=new Date(base);d.setUTCDate(base.getUTCDate()+i);dates.push(d.toISOString().slice(0,10));}const resultSets=await Promise.all(dates.map(day=>Promise.all(sports.map(s=>espnScoreboard(s,day))))),all=[...resultSets.flat(2),...(await jsonEventFeeds())],unique=new Map();for(const e of all){const key=e.canonicalId||e.eventId;if(!unique.has(key)||e.state==="in")unique.set(key,e);}return[...unique.values()].sort((a,b)=>new Date(a.start||0)-new Date(b.start||0));}
export async function parseM3U(url){const key=`m3u:${url}`,cached=cache.get(key);if(cached)return cached;const text=await fetchText(url,{},timeout),lines=text.split(/\r?\n/),channels=[];let current=null;for(const raw of lines){const line=raw.trim();if(line.startsWith("#EXTINF")){const attrs={};for(const m of line.matchAll(/([\w-]+)="([^"]*)"/g))attrs[m[1]]=m[2];current={name:line.split(",").slice(1).join(",").trim(),group:attrs["group-title"]||"",id:attrs["tvg-id"]||"",logo:attrs["tvg-logo"]||"",start:attrs["tvg-start"]||attrs["start"]||""};}else if(line&&!line.startsWith("#")&&current){channels.push({...current,url:line});current=null;}}return cache.set(key,channels,300000);}
async function m3uStreams(event){const out=[];for(const src of m3uSources){if(!src?.url)continue;try{const channels=await parseM3U(src.url),matches=channels.map(channel=>({channel,score:matchScore(channel,event)})).filter(x=>x.score>=Number(src.minScore||35)).sort((a,b)=>b.score-a.score).slice(0,8);for(const m of matches)out.push({name:`${src.name||"Authorized IPTV"} • ${m.channel.name}`,url:m.channel.url,description:`${m.channel.group||"IPTV"} • match ${m.score}%`,logo:m.channel.logo||undefined,score:m.score,priority:Number(src.priority||0),source:src.name||"m3u"});}catch{}}return out;}
async function xtreamStreams(event){const out=[];for(const src of xtreamSources){if(!src?.baseUrl||!src.username||!src.password)continue;try{const base=src.baseUrl.replace(/\/+$/,""),api=`${base}/player_api.php?username=${encodeURIComponent(src.username)}&password=${encodeURIComponent(src.password)}`,live=await fetchJson(`${api}&action=get_live_streams`,{},timeout);for(const item of Array.isArray(live)?live:[]){const channel={name:item.name||"",group:item.category_name||"",id:item.stream_id||""},score=matchScore(channel,event);if(score<Number(src.minScore||35))continue;const ext=item.container_extension||"ts";out.push({name:`${src.name||"Authorized IPTV"} • ${channel.name}`,url:`${base}/live/${encodeURIComponent(src.username)}/${encodeURIComponent(src.password)}/${encodeURIComponent(item.stream_id)}.${ext}`,description:`${channel.group||"IPTV"} • match ${score}%`,logo:item.stream_icon||undefined,score,priority:Number(src.priority||0),source:src.name||"xtream"});}}catch{}}return out;}
const NEWS_ALIASES={espn:["espn","espn hd","espn us","espn usa"],"nfl-network":["nfl network","nflnet","nfl network hd","nfl network us"],espn2:["espn2","espn 2","espn2 hd","espn2 us"],"cbs-sports-hq":["cbs sports hq","cbs sports","cbs sports network"],"fox-sports":["fox sports","fox sports 1","fs1","fox sports 2","fs2"],"mlb-network":["mlb network","mlb network hd","mlb tv"],"nba-tv":["nba tv","nba tv hd","nbatv"],"nhl-network":["nhl network","nhl network hd","nhln"]};
function newsScore(channel,aliases){const text=normalizeName(`${channel.name} ${channel.group} ${channel.id}`);let best=0;for(const alias of aliases){const a=normalizeName(alias);if(text===a)best=Math.max(best,100);else if(text.includes(a))best=Math.max(best,90);else if(normalizeName(channel.group)===a)best=Math.max(best,80);}return best;}
async function newsM3UStreams(channelId){const out=[];const aliases=NEWS_ALIASES[channelId]||[];for(const src of m3uSources){if(!src?.url)continue;try{const channels=await parseM3U(src.url),matches=channels.map(channel=>({channel,score:newsScore(channel,aliases)})).filter(x=>x.score>=Number(src.newsMinScore||src.minScore||80)).sort((a,b)=>b.score-a.score).slice(0,5);for(const m of matches)out.push({name:`${src.name||"Authorized IPTV"} • ${m.channel.name}`,title:`${m.channel.name} • Live`,url:m.channel.url,type:m.channel.url.includes(".m3u8")?"application/x-mpegURL":"video/mp4",description:`${m.channel.group||"IPTV"} • channel match ${m.score}%`,logo:m.channel.logo||undefined,score:m.score,priority:Number(src.priority||0),source:src.name||"m3u"});}catch{}}return out;}
async function newsXtreamStreams(channelId){const out=[];const aliases=NEWS_ALIASES[channelId]||[];for(const src of xtreamSources){if(!src?.baseUrl||!src.username||!src.password)continue;try{const base=src.baseUrl.replace(/\/+$/,""),api=`${base}/player_api.php?username=${encodeURIComponent(src.username)}&password=${encodeURIComponent(src.password)}`,live=await fetchJson(`${api}&action=get_live_streams`,{},timeout);for(const item of Array.isArray(live)?live:[]){const channel={name:item.name||"",group:item.category_name||"",id:item.stream_id||""},score=newsScore(channel,aliases);if(score<Number(src.newsMinScore||src.minScore||80))continue;const ext=item.container_extension||"ts";out.push({name:`${src.name||"Authorized IPTV"} • ${channel.name}`,title:`${channel.name} • Live`,url:`${base}/live/${encodeURIComponent(src.username)}/${encodeURIComponent(src.password)}/${encodeURIComponent(item.stream_id)}.${ext}`,type:"video/mp4",description:`${channel.group||"IPTV"} • channel match ${score}%`,logo:item.stream_icon||undefined,score,priority:Number(src.priority||0),source:src.name||"xtream"});}}catch{}}return out;}
export async function newsStreamsForChannel(channelId){const key=`news-streams:${channelId}`,cached=cache.get(key);if(cached)return cached;if(inFlight.has(key))return inFlight.get(key);const task=(async()=>{try{const[a,b]=await Promise.all([newsM3UStreams(channelId),newsXtreamStreams(channelId)]);return cache.set(key,rankStreams([...a,...b]).slice(0,Number(process.env.MAX_NEWS_STREAMS||6)),60000);}finally{inFlight.delete(key);}})();inFlight.set(key,task);return task;}
function directStreams(event){return directSources.filter(x=>String(x?.eventId)===String(event.eventId)&&x.url).map(x=>({name:x.name||"Authorized direct feed",url:x.url,description:x.description||"Authorized direct stream",score:100,priority:Number(x.priority||100),source:x.name||"direct"}));}
function official(event){const out=[];for(const[label,url]of Object.entries(officialLinks)){if(url&&(event.broadcast.some(b=>String(b).toLowerCase().includes(label.toLowerCase()))||String(event.league).toLowerCase().includes(label.toLowerCase())))out.push({name:`Official ${label}`,externalUrl:url,description:"Official watch page"});}return out;}
export async function streamsFor(event){const key=`streams:${event.eventId}`,cached=cache.get(key);if(cached)return cached;const[a,b]=await Promise.all([m3uStreams(event),xtreamStreams(event)]),streams=rankStreams([...directStreams(event),...a,...b]);return cache.set(key,[...streams.slice(0,Number(process.env.MAX_STREAMS_PER_EVENT||12)),...official(event)],event.state==="in"?15000:60000);}
export function providerStatus(){return{espnSports:sports,m3uSources:m3uSources.length,xtreamSources:xtreamSources.length,directSources:directSources.length,jsonFeeds:jsonFeeds.length,circuits:breakers.status(),cache:cache.statsSummary(),inFlight:inFlight.size};}
