const crypto=require('crypto');
const SPORT_WORDS=/\b(sport|sports|espn|espn\+|fox sports|fs1|fs2|tnt|nba|mlb|nhl|nfl|ncaaf|ncaab|wnba|sec network|acc network|big ten|bally|msg|regional sports|baseball|basketball|football|hockey|soccer|tennis|golf|cbs sports|nbc sports|bein|sky sport|f1|formula|racing|ufc|boxing|fight|wrestling|paramount|tsn)\b/i;
const STOP=new Set(['the','and','at','vs','v','fc','cf','sc','club','team','live','tv','hd','fhd','uhd','4k','usa','us','network','sports','sport','channel','east','west','main','backup','feed','event','plus']);
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function norm(v){return clean(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/\+/g,' plus ').replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x&&!STOP.has(x)).join(' ')}
function tokens(v){return norm(v).split(' ').filter(Boolean)}
function similarity(a,b){const aa=new Set(tokens(a)),bb=new Set(tokens(b));if(!aa.size||!bb.size)return 0;let hits=0;for(const x of aa)if(bb.has(x))hits++;return Math.round((hits/Math.min(aa.size,bb.size)*70+hits/new Set([...aa,...bb]).size*30))}
function parseTime(v){if(!v)return NaN;const n=Date.parse(String(v).replace(' ','T'));if(Number.isFinite(n))return n;const z=Number(v);return Number.isFinite(z)?(z<1e12?z*1000:z):NaN}
function withinWindow(event,channel){const a=parseTime(event.start),b=parseTime(event.end||event.start),c=parseTime(channel.start),d=parseTime(channel.end||channel.start);if(!Number.isFinite(a)||!Number.isFinite(c))return 0;const endA=Number.isFinite(b)?b:a+3*3600000,endC=Number.isFinite(d)?d:c+3*3600000;return Math.max(0,Math.min(endA,endC)-Math.max(a,c))>0?35:Math.abs(c-a)<=30*60000?20:0}
function parseM3U(text){const lines=String(text||'').split(/\r?\n/),out=[];for(let i=0;i<lines.length;i++){if(!/^#EXTINF/i.test(lines[i]))continue;const info=lines[i],url=lines[i+1]?.trim();if(!url||url.startsWith('#'))continue;out.push({name:clean((info.match(/,(.*)$/)||[])[1]||'Channel'),logo:(info.match(/tvg-logo=["']([^"']*)/i)||[])[1]||'',category:(info.match(/group-title=["']([^"']*)/i)||[])[1]||'Live TV',url,streamId:crypto.createHash('sha1').update(url).digest('hex').slice(0,12),start:'',end:''})}return out}
function epgTitle(x){return clean(x.title||x.name||x.programme||x.program_name||'')}
function epgItems(raw){const rows=Array.isArray(raw)?raw:(raw?.epg_listings||raw?.programmes||raw?.programs||[]);return rows.map(x=>({title:epgTitle(x),description:clean(x.description||x.desc||''),start:x.start||x.start_time||x.startTime||x.date||'',end:x.end||x.end_time||x.endTime||'',channelId:String(x.channel_id||x.channelId||x.stream_id||x.streamId||''),id:String(x.id||x.program_id||'')})).filter(x=>x.title)}
function isEventTitle(title){const t=clean(title);return SPORT_WORDS.test(t)&&!/^(commercial|paid program|sign off|sign-on|news|weather|music|movie|documentary|talk show|infomercial)\b/i.test(t)}
function eventKey(x){const n=norm(x.title);const t=parseTime(x.start);return `${n}|${Number.isFinite(t)?Math.floor(t/3600000):String(x.start).slice(0,13)}`}
function groupEvents(items){const map=new Map();for(const x of items){if(!isEventTitle(x.title))continue;const key=eventKey(x),old=map.get(key);if(old){if(x.end&&!old.end)old.end=x.end;if(x.channelId&&!old.channelIds.includes(x.channelId))old.channelIds.push(x.channelId);continue}map.set(key,{...x,channelIds:x.channelId?[x.channelId]:[]})}return [...map.values()].sort((a,b)=>(parseTime(a.start)||0)-(parseTime(b.start)||0))}
function eventParts(event){return tokens(`${event.title} ${event.description}`)}
function channelScore(event,channel){const epgText=`${channel.name||''} ${channel.title||''} ${channel.description||''} ${channel.category||''}`;const name=similarity(`${event.title} ${event.description}`,epgText);const eventTokens=new Set(eventParts(event)),channelTokens=new Set(tokens(epgText));let teamHits=0;for(const t of eventTokens)if(channelTokens.has(t))teamHits++;const time=withinWindow(event,channel);let network=0;const networks=['paramount','paramount plus','tsn','tsn1','tsn2','tsn3','tsn4','tsn5','espn','fox','tnt','tbs','abc','cbs','nbc','sportsnet','fight network'];const lower=epgText.toLowerCase();for(const n of networks)if(lower.includes(n))network=Math.max(network,norm(event.title).includes('ufc')&&['paramount','paramount plus','tsn','tsn1','tsn2','tsn3','tsn4','tsn5'].includes(n)?30:10);return Math.min(100,Math.round(name*.5+Math.min(teamHits,4)*7+time+network))}
function matchChannels(event,channels){return channels.map(c=>{const score=channelScore(event,c);return{...c,score}}).filter(c=>c.score>=30).sort((a,b)=>b.score-a.score).slice(0,20)}
function buildProviderEvents(epg,channels,source='xtream'){const items=epgItems(epg),events=groupEvents(items);const byId=new Map((channels||[]).map(c=>[String(c.streamId||c.channelId||c.id||''),c]));return events.map(e=>{const candidates=(channels||[]).filter(c=>!e.channelIds.length||e.channelIds.includes(String(c.streamId||c.channelId||c.id||'')));const pool=candidates.length?candidates:(channels||[]);return{id:`provider:event:${crypto.createHash('sha1').update(`${source}|${e.title}|${e.start}`).digest('hex').slice(0,16)}`,name:e.title,description:e.description,releaseInfo:e.start,start:e.start,end:e.end,source,channels:matchChannels(e,pool),providerEvent:e}})}
module.exports={parseM3U,epgItems,groupEvents,matchChannels,buildProviderEvents,isEventTitle,channelScore};