import http from "node:http";
import crypto from "node:crypto";
import { spawn } from "node:child_process";
const PUBLIC_PORT=Number(process.env.PORT||7000),INTERNAL_PORT=Number(process.env.XSPORTSX_INTERNAL_PORT||7099),PREFIX="v507",COMPAT_PREFIXES=["v507","v506","v505","v504","v503","v502","v501","v500"],BASE="http://127.0.0.1:"+INTERNAL_PORT, PUBLIC_BASE=process.env.BASE_URL||"https://xsportsx.onrender.com";
const CONFIG_SECRET=process.env.XSPORTSX_CONFIG_SECRET||crypto.randomBytes(32).toString("hex");
const KEY=crypto.createHash("sha256").update(CONFIG_SECRET).digest();
const child=spawn(process.execPath,["sports-router.js"],{env:{...process.env,PORT:String(INTERNAL_PORT),XSPORTSX_CONFIG_SECRET:CONFIG_SECRET},stdio:"inherit"});
child.on("error",e=>console.error("XSportsX router failed:",e));
child.on("exit",code=>{console.error(`XSportsX router exited: ${code}`);process.exit(code||1);});
function decode(v){try{return decodeURIComponent(v)}catch{return v}}
function encryptConfig(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",KEY,iv),data=Buffer.concat([c.update(JSON.stringify(v),"utf8"),c.final()]);return Buffer.concat([iv,c.getAuthTag(),data]).toString("base64url")}
function configurePage(prefix=PREFIX){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>XSportsX Configuration</title><style>body{margin:0;background:#08090c;color:#fff;font:16px system-ui;display:grid;place-items:center;min-height:100vh}main{width:min(520px,92vw);background:#12151b;padding:28px;border-radius:18px;border:1px solid #2a303a}label{display:block;margin:15px 0 7px}input{width:100%;box-sizing:border-box;padding:13px;border-radius:9px;border:1px solid #343a46;background:#090b10;color:#fff}button{width:100%;padding:14px;margin-top:20px;border:0;border-radius:9px;background:#e21d2d;color:#fff;font-weight:700}small{color:#9aa2ad}</style></head><body><main><h1>🏆 XSportsX</h1><p>Configure your authorized Xtream account.</p><form method="post" action="/${prefix}/configure"><label>Server URL</label><input name="server" required placeholder="https://provider.example:8080"><label>Username</label><input name="username" required autocomplete="username"><label>Password</label><input name="password" type="password" required autocomplete="current-password"><button>GENERATE NUVIO MANIFEST</button></form><p><small>Credentials are encrypted into the generated manifest token.</small></p></main></body></html>`}
function readyPage(url){return `<!doctype html><html><body style="background:#08090c;color:#fff;font:16px system-ui;padding:30px"><main style="max-width:700px;margin:auto"><h1>✅ XSportsX Ready</h1><p>Copy this manifest URL into Nuvio.</p><input style="width:100%;box-sizing:border-box;padding:14px" readonly value="${url.replace(/&/g,"&amp;").replace(/"/g,"&quot;")}"><p><a style="color:#fff" href="${url}">Open manifest</a></p></main></body></html>`}
function prefixIndex(parts){return parts.findIndex(x=>COMPAT_PREFIXES.includes(x))}
function proxyPath(original){const u=new URL(original,"http://localhost"),parts=u.pathname.split("/").filter(Boolean),i=prefixIndex(parts);if(i<0)return{path:u.pathname,query:u.search};const rest=parts.slice(i+1);if(!rest.length)return{path:"/manifest.json",query:""};if(rest[0]==="configure"||rest[0]==="manifest.json"||rest[0]==="health")return{path:"/"+rest[0],query:u.search};const token=decode(rest[0]),resource=rest.slice(1).map(decode),q=new URLSearchParams(u.search);q.set("config",token);return{path:"/"+resource.join("/"),query:q.toString()?"?"+q.toString():""};}
async function handleConfigure(req,res,prefix){if(req.method==="GET"){res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-xsportsx-proxy":"v507-compatible"});return res.end(configurePage(prefix));}if(req.method==="POST"){let body="";for await(const chunk of req)body+=chunk;const f=new URLSearchParams(body),server=String(f.get("server")||"").trim().replace(/\/+$/,""),username=String(f.get("username")||"").trim(),password=String(f.get("password")||"");if(!/^https?:\/\//i.test(server)||!username||!password){res.writeHead(400,{"content-type":"text/plain; charset=utf-8"});return res.end("Invalid Xtream configuration");}const token=encryptConfig({server,username,password}),url=`${PUBLIC_BASE}/${PREFIX}/${token}/manifest.json`;res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-xsportsx-proxy":"v507-compatible"});return res.end(readyPage(url));}res.writeHead(405,{allow:"GET, POST"});res.end();}
const server=http.createServer(async(req,res)=>{try{const raw=req.url||"/",u=new URL(raw,"http://localhost"),parts=u.pathname.split("/").filter(Boolean),i=prefixIndex(parts);if((i>=0&&parts[i+1]==="configure")||u.pathname==="/configure")return handleConfigure(req,res,i>=0?parts[i]:PREFIX);const p=proxyPath(raw),target=new URL(p.path+p.query,BASE),up=http.request(target,{method:req.method,headers:{...req.headers,host:`127.0.0.1:${INTERNAL_PORT}`,connection:"keep-alive"}},ur=>{const headers={...ur.headers,"cache-control":ur.headers["cache-control"]||"no-store","x-xsportsx-proxy":"v507-compatible"};res.writeHead(ur.statusCode||502,headers);ur.pipe(res)});up.on("error",e=>{if(!res.headersSent)res.writeHead(502,{"content-type":"application/json"});res.end(JSON.stringify({error:"XSportsX upstream unavailable",detail:String(e.message||e)}))});req.pipe(up);}catch(e){res.writeHead(502,{"content-type":"application/json"});res.end(JSON.stringify({error:String(e.message||e)}))}});
server.keepAliveTimeout=120000;server.headersTimeout=125000;server.requestTimeout=120000;server.listen(PUBLIC_PORT,"0.0.0.0",()=>console.log(`XSportsX compatible proxy listening on ${PUBLIC_PORT}; internal on ${INTERNAL_PORT}`));