import http from "node:http";
import crypto from "node:crypto";

const PORT=Number(process.env.PORT||7000);
const PREFIX="v524";
const VERSION="5.0.24";
const BASE=process.env.BASE_URL||"https://xsportsx.onrender.com";
const SECRET=process.env.XSPORTSX_CONFIG_SECRET||"xsportsx-v520-stable-config-key";
const KEY=crypto.createHash("sha256").update(SECRET).digest();
const cache=new Map();
const LEAGUES={nfl:["football","nfl","🏈","NFL"],ncaaf:["football","college-football","🏈","NCAA Football"],nba:["basketball","nba","🏀","NBA"],nhl:["hockey","nhl","🏒","NHL"],mlb:["baseball","mlb","⚾","MLB"],soccer:["soccer","eng.1","⚽","Soccer"],ufc:["mma","ufc","🥊","UFC"]};
const NEWS={ESPN:["espn","espn2","espnu","espn news","espnews","espn deportes","espn+","espn plus"],"ACC Network":["acc network","accn"],"SEC Network":["sec network","secn"],"Big Ten Network":["big ten network","btn"],"NFL Network":["nfl network","nfln"],"MLB Network":["mlb network","mlbn"],"NBA TV":["nba tv","nbatv"],"NHL Network":["nhl network","nhln"],"CBS Sports":["cbs sports network","cbs sports","cbssn"],"Fox Sports":["fox sports","fox sports 1","fox sports 2","fs1","fs2"],"Golf Channel":["golf channel"],"TNT Sports":["tnt sports","tnt"],"NBC Sports":["nbc sports"],"beIN Sports":["bein sports","beinsports"],Sportsnet:["sportsnet"],"Tennis Channel":["tennis channel"]};
const FALLBACK={ESPN:"https://cdn.simpleicons.org/espn","NFL Network":"https://cdn.simpleicons.org/nfl","MLB Network":"https://cdn.simpleicons.org/mlb","NBA TV":"https://cdn.simpleicons.org/nba","NHL Network":"https://cdn.simpleicons.org/nhl","CBS Sports":"https://cdn.simpleicons.org/cbs","Fox Sports":"https://cdn.simpleicons.org/fox","Golf Channel":"https://cdn.simpleicons.org/golf","Tennis Channel":"https://cdn.simpleicons.org/tennis",Sportsnet:"https://cdn.simpleicons.org/sportsnet"};
const catalogs=[
 ["sports-command-center","🏆 XSPORTSX • SPORTS COMMAND CENTER"],["live-now","🔴 LIVE NOW"],["starting-soon","⏰ STARTING SOON"],["sports-news-v2","📰 SPORTS NEWS NETWORKS"],["nfl","🏈 NFL"],["ncaaf","🏈 NCAA FOOTBALL"],["nba","🏀 NBA"],["nhl","🏒 NHL"],["mlb","⚾ MLB"],["ufc-v2","🥊 UFC COMMAND CENTER"],["soccer","⚽ SOCCER"],["iptv-live","📡 MY IPTV • LIVE TV"]
];
const norm=s=>String(s||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const json=(res,b,status=200,max=0)=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":max?`public,max-age=${max},stale-while-revalidate=60`:"no-store","access-control-allow-origin":"*","x-xsportsx-version":VERSION});res.end(JSON.stringify(b))};
const enc=v=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",KEY,iv),d=Buffer.concat([c.update(JSON.stringify(v),"utf8"),c.final()]);return Buffer.concat([iv,c.getAuthTag(),d]).toString("base64url")};
const dec=t=>{try{const r=Buffer.from(t,"base64url");if(r.length<29)return null;const d=crypto.createDecipheriv("aes-256-gcm",KEY,r.subarray(0,12));d.setAuthTag(r.subarray(12,28));const v=JSON.parse(Buffer.concat([d.update(r.subarray(28)),d.final()]).toString());return v?.server&&v?.username&&v?.password?{server:String(v.server).replace(/\/+$/,""),username:String(v.username),password:String(v.password)}:null}catch{return null}};
async function get(url,timeout=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{accept:"application/json","user-agent":`XSportsX/${VERSION}`}});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function xtUrl(c,a=""){const u=new URL(`${c.server}/player_api.php`);u.searchParams.set("username",c.username);u.searchParams.set("password",c.password);if(a)u.searchParams.set("action",a);return u.toString()}
async function xt(c,a=""){const k=`xt:${c.server}|${c.username}|${a}`,h=cache.get(k);if(h&&Date.now()-h.t<120000)return h.v;try{const v=await get(xtUrl(c,a));cache.set(k,{t:Date.now(),v});return v}catch{return h?.v||null}}
async function xtStreams(c){const k=`streams:${c.server}|${c.username}`,h=cache.get(k);if(h&&Date.now()-h.t<120000)return h.v;const [cats,streams]=await Promise.all([xt(c,"get_live_categories"),xt(c,"get_live_streams")]);const cm=new Map((Array.isArray(cats)?cats:[]).map(x=>[String(x.category_id),String(x.category_name||"Live TV")]));const v=(Array.isArray(streams)?streams:[]).map(s=>({id:String(s.stream_id),name:String(s.name||`Channel ${s.stream_id}`),icon:s.stream_icon||"",cat:cm.get(String(s.category_id))||String(s.category_name||"Live TV"),url:`${c.server}/live/${encodeURIComponent(c.username)}/${encodeURIComponent(c.password)}/${encodeURIComponent(s.stream_id)}.${String(s.container_extension||"ts").replace(/[^a-z0-9]/gi,"")||"ts"}`}));cache.set(k,{t:Date.now(),v});return v}
function token(path){const p=path.split("/").filter(Boolean),i=p.indexOf(PREFIX);return i>=0?p[i+1]&&p[i+1]!=="manifest.json"&&p[i+1]!=="configure"&&p[i+1]!=="health"?decodeURIComponent(p[i+1]):null:null}
function manifest(configured=false){return{id:"com.xsportsx.sports.epg.v524",version:VERSION,name:"XSportsX Sports Command Center",description:"Fast sports EPG with authorized Xtream live TV, sports news and UFC events.",resources:[{name:"catalog",types:["channel"]},{name:"meta",types:["channel"]},{name:"stream",types:["channel"]}],types:["channel"],catalogs:catalogs.map(([id,name])=>({type:"channel",id,name,extra:[],showInHome:true})),behaviorHints:{configurable:!configured,configurationRequired:!configured},config:configured?undefined:[{key:"server",type:"text",title:"Xtream Server URL",required:true},{key:"username",type:"text",title:"Xtream Username",required:true},{key:"password",type:"password",title:"Xtream Password",required:true}]};}
function eventMeta(e,league){const c=e.competitions?.[0],teams=c?.competitors||[],home=teams.find(x=>x.homeAway==="home")?.team||teams[0]?.team||{},away=teams.find(x=>x.homeAway==="away")?.team||teams[1]?.team||{},name=league==="ufc"?(e.name||e.shortName||"UFC Event"):`${away.displayName||"TBD"} vs ${home.displayName||"TBD"}`;if(league!=="ufc"&&!home.displayName&&!away.displayName)return null;const poster=league==="ufc"?`${BASE}/${PREFIX}/assets/ufc.svg`:home.logo||home.logos?.[0]?.href||away.logo||away.logos?.[0]?.href||"";return{id:`sport:${league}:${e.id}`,type:"channel",name,poster,background:poster,description:`${LEAGUES[league][3]} • ${LEAGUES[league][4]}\n${c?.status?.type?.shortDetail||"Scheduled"}\n${e.date||""}`,releaseInfo:e.date||"",genres:["Sports",LEAGUES[league][4]],behaviorHints:{isLive:c?.status?.type?.state==="in"},event:{id:String(e.id),league,start:e.date||"",state:c?.status?.type?.state||"pre",home:{name:home.displayName||"TBD",short:home.abbreviation||""},away:{name:away.displayName||"TBD",short:away.abbreviation||""}}};}
async function leagueEvents(id){const [sport,slug]=LEAGUES[id];const k=`espn:${id}`,h=cache.get(k);if(h&&Date.now()-h.t<30000)return h.v;try{const d=await get(`https://site.api.espn.com/apis/site/v2/sports/${sport}/${slug}/scoreboard?limit=100`);const v=(d.events||[]).map(e=>eventMeta(e,id)).filter(Boolean);cache.set(k,{t:Date.now(),v});return v}catch{return h?.v||[]}}
async function allEvents(){const a=await Promise.all(Object.keys(LEAGUES).map(leagueEvents));return a.flat().sort((a,b)=>new Date(a.releaseInfo)-new Date(b.releaseInfo));}
function newsGroup(name,cat){const v=norm(`${name} ${cat}`);for(const [g,terms] of Object.entries(NEWS))if(terms.some(x=>v.includes(norm(x))))return g;return null}
async function newsCatalog(c,id){const rows=await xtStreams(c);if(id==="iptv-live")return rows.slice(0,200).map(s=>({id:`xtream:${s.id}`,type:"channel",name:s.name,poster:s.icon||undefined,background:s.icon||undefined,description:s.cat,genres:["IPTV",s.cat],behaviorHints:{isLive:true}}));const groups=Object.keys(NEWS);const group=id==="sports-news-v2"?null:groups.find(g=>`news-${norm(g).replace(/\s+/g,"-")}`===id);const filtered=rows.filter(s=>{const g=newsGroup(s.name,s.cat);return group?g===group:!!g});if(group){const icon=filtered.find(x=>x.icon)?.icon||FALLBACK[group]||"";return [{id:`news-group:${norm(group).replace(/\s+/g,"-")}`,type:"channel",name:group,poster:icon,background:icon,description:`${filtered.length} ${group} channel${filtered.length===1?"":"s"}`,genres:["Sports News",group]}];}return groups.map(g=>{const r=rows.filter(s=>newsGroup(s.name,s.cat)===g),icon=r.find(x=>x.icon)?.icon||FALLBACK[g]||"";return{id:`news-group:${norm(g).replace(/\s+/g,"-")}`,type:"channel",name:g,poster:icon,background:icon,description:r.length?`${r.length} channel${r.length===1?"":"s"}`:`${g} — no matching channel`,genres:["Sports News",g]}}).filter(x=>x.description.includes("channel"));}
async function catalog(c,id){if(id==="sports-news-v2"||id.startsWith("news-")||id==="iptv-live")return{metas:await newsCatalog(c,id)};if(id==="sports-command-center")return{metas:(await allEvents()).slice(0,200)};if(id==="live-now")return{metas:(await allEvents()).filter(x=>x.behaviorHints?.isLive).slice(0,100)};if(id==="starting-soon")return{metas:(await allEvents()).filter(x=>!x.behaviorHints?.isLive&&new Date(x.releaseInfo).getTime()<Date.now()+48*3600000).slice(0,100)};const league=Object.keys(LEAGUES).find(x=>x===id||(`${x}-v2`===id));return{metas:league?await leagueEvents(league):[]};}
function findStream(rows,m){const target=norm(`${m.name} ${m.description||""}`);return rows.filter(s=>{const n=norm(`${s.name} ${s.cat}`);const words=target.split(" ").filter(x=>x.length>2);let score=0;for(const w of words)if(n.includes(w))score++;return score>=2}).sort((a,b)=>b.name.length-a.name.length).slice(0,8)}
async function routeApi(req,res,c,parts){const i=parts.indexOf(PREFIX),rest=parts.slice(i+2);if(rest[0]==="catalog"&&rest[1]==="channel"&&rest[2])return json(res,await catalog(c,rest[2].replace(/\.json$/,"")),200,20);if(rest[0]==="meta"&&rest[1]==="channel"&&rest[2]){const id=decodeURIComponent(rest[2].replace(/\.json$/,""));if(id.startsWith("sport:")){const [_,lg,eid]=id.split(":");const m=(await leagueEvents(lg)).find(x=>x.id===id);return json(res,{meta:m||{id,type:"channel",name:"Event"}})}if(id.startsWith("xtream:")){const sid=id.split(":")[1],s=(await xtStreams(c)).find(x=>x.id===sid);return json(res,{meta:s?{id,type:"channel",name:s.name,poster:s.icon,background:s.icon,description:s.cat,genres:["IPTV",s.cat],behaviorHints:{isLive:true}}:{id,type:"channel",name:"Channel"}})}if(id.startsWith("news-group:")){const g=id.slice(11),rows=(await xtStreams(c)).filter(s=>norm(newsGroup(s.name,s.cat))===norm(g));const first=rows[0];return json(res,{meta:{id,type:"channel",name:Object.keys(NEWS).find(x=>norm(x).replace(/\s+/g,"-")===g)||g,poster:first?.icon||FALLBACK[Object.keys(NEWS).find(x=>norm(x).replace(/\s+/g,"-")===g)]||"",description:`${rows.length} channel(s)`}})}return json(res,{meta:{id,type:"channel",name:"XSportsX"}})}if(rest[0]==="stream"&&rest[1]==="channel"&&rest[2]){const id=decodeURIComponent(rest[2].replace(/\.json$/,""));if(id.startsWith("xtream:")){const s=(await xtStreams(c)).find(x=>x.id===id.split(":")[1]);return json(res,{streams:s?[{name:s.name,url:s.url,behaviorHints:{notWebReady:true}}]:[]})}if(id.startsWith("sport:")){const [_,lg,eid]=id.split(":"),m=(await leagueEvents(lg)).find(x=>x.id===id),rows=await xtStreams(c),matches=m?findStream(rows,m):[];return json(res,{streams:matches.map(s=>({name:`▶ ${s.name}`,url:s.url,title:s.name,description:s.cat}))})}if(id.startsWith("news-group:")){const g=id.slice(11),rows=(await xtStreams(c)).filter(s=>norm(newsGroup(s.name,s.cat))===norm(g));return json(res,{streams:rows.map(s=>({name:`▶ ${s.name}`,url:s.url,title:s.name,description:s.cat}))})}return json(res,{streams:[]})}return json(res,{error:"Not found"},404)}
async function configure(req,res){if(req.method==="GET"){res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"});return res.end(`<html><body style="background:#08090c;color:#fff;font:16px system-ui;padding:30px"><h1>XSportsX ${VERSION}</h1><form method="post" action="/${PREFIX}/configure"><input name="server" placeholder="Xtream Server URL" required style="display:block;padding:12px;width:100%;box-sizing:border-box;margin:8px 0"><input name="username" placeholder="Username" required style="display:block;padding:12px;width:100%;box-sizing:border-box;margin:8px 0"><input name="password" type="password" placeholder="Password" required style="display:block;padding:12px;width:100%;box-sizing:border-box;margin:8px 0"><button style="padding:14px;width:100%">Generate Manifest</button></form></body></html>`)}else{let b="";for await(const x of req)b+=x;const f=new URLSearchParams(b),server=String(f.get("server")||"").trim().replace(/\/+$/,""),username=String(f.get("username")||"").trim(),password=String(f.get("password")||"");if(!/^https?:\/\//i.test(server)||!username||!password)return json(res,{error:"Invalid Xtream configuration"},400);const u=`${BASE}/${PREFIX}/${enc({server,username,password})}/manifest.json`;res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"});res.end(`<html><body style="background:#08090c;color:#fff;font:16px system-ui;padding:30px"><h1>XSportsX ${VERSION} Ready</h1><p>Copy this manifest URL into Nuvio:</p><input readonly style="width:100%;padding:14px;box-sizing:border-box" value="${u}"><p>${u}</p></body></html>`);}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||"/","http://localhost"),p=u.pathname;if(p==="/health"||p===`/${PREFIX}/health`)return json(res,{ok:true,version:VERSION,service:"xsportsx"});if(p===`/${PREFIX}/configure`)return configure(req,res);if(p===`/${PREFIX}/manifest.json`)return json(res,manifest(false));const t=token(p);if(t&&p.endsWith("/manifest.json")){if(!dec(t))return json(res,{error:"Invalid configuration token"},400);return json(res,manifest(true))}if(t){const c=dec(t);if(!c)return json(res,{error:"Invalid configuration token"},400);const parts=p.split("/").filter(Boolean);return routeApi(req,res,c,parts)}return json(res,{service:"XSportsX",version:VERSION},200)}catch(e){console.error(e);return json(res,{error:String(e.message||e)},500)}});
server.keepAliveTimeout=120000;server.headersTimeout=125000;server.listen(PORT,"0.0.0.0",()=>console.log(`XSportsX ${VERSION} listening on ${PORT}`));
