import http from "node:http";
import { spawn } from "node:child_process";
const PUBLIC_PORT=Number(process.env.PORT||7000),INTERNAL_PORT=Number(process.env.XSPORTSX_INTERNAL_PORT||7099),PREFIX="v502",BASE="http://127.0.0.1:"+INTERNAL_PORT;
const child=spawn(process.execPath,["sports-router.js"],{env:{...process.env,PORT:String(INTERNAL_PORT)},stdio:"inherit"});
child.on("error",e=>console.error("XSportsX router failed:",e));
child.on("exit",code=>{console.error(`XSportsX router exited: ${code}`);process.exit(code||1);});
function decode(v){try{return decodeURIComponent(v)}catch{return v}}
function proxyPath(original){const u=new URL(original,"http://localhost"),parts=u.pathname.split("/").filter(Boolean),i=parts.indexOf(PREFIX);if(i<0)return{path:u.pathname,query:u.search};const rest=parts.slice(i+1);if(!rest.length)return{path:"/manifest.json",query:""};if(rest[0]==="configure"||rest[0]==="manifest.json"||rest[0]==="health")return{path:"/"+rest[0],query:u.search};const token=decode(rest[0]),resource=rest.slice(1).map(decode),q=new URLSearchParams(u.search);q.set("config",token);return{path:"/"+resource.join("/"),query:q.toString()?"?"+q.toString():""};}
const server=http.createServer((req,res)=>{try{const p=proxyPath(req.url||"/"),target=new URL(p.path+p.query,BASE),up=http.request(target,{method:req.method,headers:{...req.headers,host:`127.0.0.1:${INTERNAL_PORT}`,connection:"keep-alive"}},ur=>{const headers={...ur.headers,"cache-control":ur.headers["cache-control"]||"no-store","x-xsportsx-proxy":"v502"};res.writeHead(ur.statusCode||502,headers);ur.pipe(res)});up.on("error",e=>{if(!res.headersSent)res.writeHead(502,{"content-type":"application/json"});res.end(JSON.stringify({error:"XSportsX upstream unavailable",detail:String(e.message||e)}))});req.pipe(up)}catch(e){res.writeHead(502,{"content-type":"application/json"});res.end(JSON.stringify({error:String(e.message||e)}))}});
server.keepAliveTimeout=120000;server.headersTimeout=125000;server.requestTimeout=120000;server.listen(PUBLIC_PORT,"0.0.0.0",()=>console.log(`XSportsX v502 proxy listening on ${PUBLIC_PORT}; internal on ${INTERNAL_PORT}`));