import { URL } from 'node:url';

const MIN_SOURCES = Number(process.env.MIN_SPORTS_SOURCES || 5);
const FETCH_TIMEOUT_MS = Number(process.env.SOURCE_FETCH_TIMEOUT_MS || 7000);
const HEALTH_TIMEOUT_MS = Number(process.env.SOURCE_HEALTH_TIMEOUT_MS || 5000);
const CONFIGURED_SOURCE_URLS = String(process.env.BASE64_SOURCE_URLS || process.env.XSPORTSX_SOURCE_URL || '')
  .split(/[\n,]+/).map(x => x.trim()).filter(Boolean).slice(0, 20);
const URL_RE = /https?:\/\/[^\s"'<>]+/gi;
const MEDIA_RE = /\.(?:m3u8?|mpd|ts)(?:$|[?#])/i;
const IPTV_PATH_RE = /(?:get\.php|player_api\.php|panel_api\.php|xmltv\.php|portal\.php|stalker)/i;
const CREDENTIAL_RE = /(?:player_api\.php|get\.php|panel_api\.php|xmltv\.php).*?(?:username|password)=/i;
const SPORTS_SITES = ['espn.com','plus.espn.com','foxsports.com','nbcsports.com','cbssports.com','nfl.com','nba.com','nhl.com','mlb.com','nascar.com','f1.com','ufc.com','wwe.com','pga.com','fifa.com','uefa.com','redbull.com','youtube.com'];
function usablePublicUrl(raw){try{const cleaned=raw.replace(/[),.;]+$/,'').replace(/&amp;/g,'&');const u=new URL(cleaned);if(!['http:','https:'].includes(u.protocol))return null;if(CREDENTIAL_RE.test(u.toString()))return null;if(/\/login(?:\/|$)|\/signin(?:\/|$)|\/account(?:\/|$)/i.test(u.pathname))return null;return u.toString()}catch{return null}}
function decodeBase64(value){let s=String(value||'').trim().replace(/\s+/g,'').replace(/-/g,'+').replace(/_/g,'/');if(!s||!/^[A-Za-z0-9+/=_-]+$/.test(s))return'';s+='='.repeat((4-s.length%4)%4);try{return Buffer.from(s,'base64').toString('utf8')}catch{return''}}
function extractUrls(text){const out=new Set(),raw=String(text||'');for(const m of raw.matchAll(URL_RE)){const u=usablePublicUrl(m[0]);if(u)out.add(u)}for(const token of raw.split(/\s+/)){if(token.length<20||token.length>8192)continue;const decoded=decodeBase64(token);for(const m of decoded.matchAll(URL_RE)){const u=usablePublicUrl(m[0]);if(u)out.add(u)}}return[...out]}
function extractPageLinks(text,baseUrl){const out=new Set();const raw=String(text||'');for(const m of raw.matchAll(/(?:href|src)\s*=\s*["']([^"']+)["']/gi)){try{const u=usablePublicUrl(new URL(m[1],baseUrl).toString());if(u)out.add(u)}catch{}}for(const u of extractUrls(raw))out.add(u);return[...out]}
function looksLikeIptvInfo(text,url=''){const s=(String(text||'')+' '+String(url||'')).toLowerCase();return s.includes('#extm3u')||s.includes('#extinf')||MEDIA_RE.test(url)||IPTV_PATH_RE.test(url)||s.includes('m3u_plus')||s.includes('playlist')}
async function fetchText(url,timeout=FETCH_TIMEOUT_MS){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{signal:ctl.signal,redirect:'follow',headers:{'user-agent':'XSportsX-source-finder/4.0','accept':'text/html,text/plain,application/vnd.apple.mpegurl,application/x-mpegURL,application/json,*/*'}});return r.ok?await r.text():''}catch{return''}finally{clearTimeout(timer)}}
async function resolveConfiguredPage(url){const page=await fetchText(url);if(!page)return[];const direct=extractUrls(page),links=extractPageLinks(page,url);const candidates=new Set([...direct,...links.filter(x=>looksLikeIptvInfo(page,x))]);
  // Follow one level from the decoded destination. This is the key step: a Base64
  // value that points to a paste/page is not itself the IPTV source. We inspect the
  // destination for the actual public playlist/media URL before health checking it.
  for(const link of links.slice(0,40)){const body=await fetchText(link);if(!body)continue;for(const u of extractPageLinks(body,link))if(looksLikeIptvInfo(body,u)||MEDIA_RE.test(u))candidates.add(u);if(looksLikeIptvInfo(body,link))candidates.add(link)}
  return [...candidates];}
async function configuredSources(urls){const safe=(urls||[]).map(String).filter(Boolean).slice(0,20);if(!safe.length)return[];const discovered=new Set();for(const u of safe){for(const x of await resolveConfiguredPage(u))discovered.add(x);if(looksLikeIptvInfo('',u))discovered.add(u)}return[...discovered]}
async function webSearch(query){const q=encodeURIComponent(query),html=await fetchText(`https://html.duckduckgo.com/html/?q=${q}`);return extractUrls(html)}
async function discoverSportsWeb(event={}){const terms=[event.home,event.away,event.name,event.league,event.sport].filter(Boolean).join(' '),base=terms||'live sports';const queries=[`${base} ESPN live`,`${base} FOX Sports live`,`${base} NBC Sports live`,`${base} CBS Sports live`,`${base} official stream`,`${base} where to watch`,`${base} live video`,`${base} highlights`,`${base} SportsCenter`,`${base} UFC live`,`${base} MMA live`];const found=new Set();for(const q of queries)for(const u of await webSearch(q))found.add(u);return[...found].filter(u=>SPORTS_SITES.some(h=>{try{return new URL(u).hostname.endsWith(h)}catch{return false}})||MEDIA_RE.test(u))}
async function iptvOrgSports(){const urls=['https://iptv-org.github.io/iptv/categories/sports.m3u','https://iptv-org.github.io/api/streams.json'];return(await Promise.all(urls.map(fetchText))).flatMap(t=>extractUrls(t))}
async function healthCheck(url){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),HEALTH_TIMEOUT_MS),started=Date.now();try{const r=await fetch(url,{method:'GET',signal:ctl.signal,redirect:'follow',headers:{'user-agent':'XSportsX-health/4.0',range:'bytes=0-4095'} }),type=(r.headers.get('content-type')||'').toLowerCase(),finalUrl=r.url||url,media=MEDIA_RE.test(finalUrl)||IPTV_PATH_RE.test(finalUrl)||/mpegurl|dash|m3u|video|octet-stream/i.test(type);return{url,ok:r.ok&&media,latencyMs:Date.now()-started,status:r.status,contentType:type,finalUrl}}catch(error){return{url,ok:false,latencyMs:Date.now()-started,error:error?.name||'fetch_failed'}}finally{clearTimeout(timer)}}
export async function findConfiguredSources(urls=[]){const discovered=new Set(await configuredSources(urls)),candidates=[...discovered].slice(0,500),checks=await Promise.all(candidates.map(healthCheck));return checks.filter(x=>x.ok).sort((a,b)=>a.latencyMs-b.latencyMs).slice(0,Math.max(MIN_SOURCES,48))}
export async function findPublicSportsSources(event={}){const configured=await findConfiguredSources(CONFIGURED_SOURCE_URLS),discovered=new Set(configured.map(x=>x.url));for(const u of await iptvOrgSports())discovered.add(u);for(const u of await discoverSportsWeb(event))discovered.add(u);const candidates=[...discovered].slice(0,500),checks=await Promise.all(candidates.map(healthCheck));return checks.filter(x=>x.ok).sort((a,b)=>a.latencyMs-b.latencyMs).slice(0,Math.max(MIN_SOURCES,48))}
export async function replenishSources(existing=[],event={}){const healthy=existing.filter(x=>x?.url);if(healthy.length>=MIN_SOURCES)return healthy;const found=await findPublicSportsSources(event),seen=new Set(healthy.map(x=>x.url));for(const item of found){if(!seen.has(item.url)){healthy.push({...item,source:'public-sports-web-discovery'});seen.add(item.url)}if(healthy.length>=MIN_SOURCES)break}return healthy}
export{MIN_SOURCES};
